const proSamples = [
  {
    id: 'customize-1',
    artist: 'customize',
    name: "808 1 B",
    src: "/audio/pro/customize/808 1 B.mp3",
  },
  {
    id: 'customize-2',
    artist: 'customize',
    name: "808 1 E",
    src: "/audio/pro/customize/808 1 E.mp3",
  },
  {
    id: 'customize-3',
    artist: 'customize',
    name: "808 2 D",
    src: "/audio/pro/customize/808 2 D.mp3",
  },
  {
    id: 'customize-4',
    artist: 'customize',
    name: "808 2 E",
    src: "/audio/pro/customize/808 2 E.mp3",
  },
  {
    id: 'customize-5',
    artist: 'customize',
    name: "808 3 C",
    src: "/audio/pro/customize/808 3 C.mp3",
  },
  {
    id: 'customize-6',
    artist: 'customize',
    name: "808 3 E",
    src: "/audio/pro/customize/808 3 E.mp3",
  },
  {
    id: 'customize-7',
    artist: 'customize',
    name: "808 4 C",
    src: "/audio/pro/customize/808 4 C.mp3",
  },
  {
    id: 'customize-8',
    artist: 'customize',
    name: "808 5 B",
    src: "/audio/pro/customize/808 5 B.mp3",
  },
  {
    id: 'customize-9',
    artist: 'customize',
    name: "Bass B",
    src: "/audio/pro/customize/Bass B.mp3",
  },
  {
    id: 'customize-10',
    artist: 'customize',
    name: "Clap 1",
    src: "/audio/pro/customize/Clap 1.mp3",
  },
  {
    id: 'customize-11',
    artist: 'customize',
    name: "Clap 2",
    src: "/audio/pro/customize/Clap 2.mp3",
  },
  {
    id: 'customize-12',
    artist: 'customize',
    name: "Clap 3",
    src: "/audio/pro/customize/Clap 3.mp3",
  },
  {
    id: 'customize-13',
    artist: 'customize',
    name: "Clap 4",
    src: "/audio/pro/customize/Clap 4.mp3",
  },
  {
    id: 'customize-14',
    artist: 'customize',
    name: "Clap 5",
    src: "/audio/pro/customize/Clap 5.mp3",
  },
  {
    id: 'customize-15',
    artist: 'customize',
    name: "Crash 1",
    src: "/audio/pro/customize/Crash 1.mp3",
  },
  {
    id: 'customize-16',
    artist: 'customize',
    name: "Crash 2",
    src: "/audio/pro/customize/Crash 2.mp3",
  },
  {
    id: 'customize-17',
    artist: 'customize',
    name: "Crash1",
    src: "/audio/pro/customize/Crash1.mp3",
  },
  {
    id: 'customize-18',
    artist: 'customize',
    name: "Fx 1",
    src: "/audio/pro/customize/Fx 1.mp3",
  },
  {
    id: 'customize-19',
    artist: 'customize',
    name: "Fx 2",
    src: "/audio/pro/customize/Fx 2.mp3",
  },
  {
    id: 'customize-20',
    artist: 'customize',
    name: "Fx 3",
    src: "/audio/pro/customize/Fx 3.mp3",
  },
  {
    id: 'customize-21',
    artist: 'customize',
    name: "Fx 4",
    src: "/audio/pro/customize/Fx 4.mp3",
  },
  {
    id: 'customize-22',
    artist: 'customize',
    name: "HH 1",
    src: "/audio/pro/customize/HH 1.mp3",
  },
  {
    id: 'customize-23',
    artist: 'customize',
    name: "HH 2",
    src: "/audio/pro/customize/HH 2.mp3",
  },
  {
    id: 'customize-24',
    artist: 'customize',
    name: "HH 3",
    src: "/audio/pro/customize/HH 3.mp3",
  },
  {
    id: 'customize-25',
    artist: 'customize',
    name: "HH 4",
    src: "/audio/pro/customize/HH 4.mp3",
  },
  {
    id: 'customize-26',
    artist: 'customize',
    name: "HH 5",
    src: "/audio/pro/customize/HH 5.mp3",
  },
  {
    id: 'customize-27',
    artist: 'customize',
    name: "HH 6",
    src: "/audio/pro/customize/HH 6.mp3",
  },
  {
    id: 'customize-28',
    artist: 'customize',
    name: "HH 7",
    src: "/audio/pro/customize/HH 7.mp3",
  },
  {
    id: 'customize-29',
    artist: 'customize',
    name: "HH 8",
    src: "/audio/pro/customize/HH 8.mp3",
  },
  {
    id: 'customize-30',
    artist: 'customize',
    name: "HH 9",
    src: "/audio/pro/customize/HH 9.mp3",
  },
  {
    id: 'customize-31',
    artist: 'customize',
    name: "Kick 1",
    src: "/audio/pro/customize/Kick 1.mp3",
  },
  {
    id: 'customize-32',
    artist: 'customize',
    name: "Kick 2",
    src: "/audio/pro/customize/Kick 2.mp3",
  },
  {
    id: 'customize-33',
    artist: 'customize',
    name: "Kick 3",
    src: "/audio/pro/customize/Kick 3.mp3",
  },
  {
    id: 'customize-34',
    artist: 'customize',
    name: "Kick 4",
    src: "/audio/pro/customize/Kick 4.mp3",
  },
  {
    id: 'customize-35',
    artist: 'customize',
    name: "Kick 5",
    src: "/audio/pro/customize/Kick 5.mp3",
  },
  {
    id: 'customize-36',
    artist: 'customize',
    name: "Kick 6",
    src: "/audio/pro/customize/Kick 6.mp3",
  },
  {
    id: 'customize-37',
    artist: 'customize',
    name: "Kick 7",
    src: "/audio/pro/customize/Kick 7.mp3",
  },
  {
    id: 'customize-38',
    artist: 'customize',
    name: "OH 1",
    src: "/audio/pro/customize/OH 1.mp3",
  },
  {
    id: 'customize-39',
    artist: 'customize',
    name: "OH 2",
    src: "/audio/pro/customize/OH 2.mp3",
  },
  {
    id: 'customize-40',
    artist: 'customize',
    name: "OH 3",
    src: "/audio/pro/customize/OH 3.mp3",
  },
  {
    id: 'customize-41',
    artist: 'customize',
    name: "OH 4",
    src: "/audio/pro/customize/OH 4.mp3",
  },
  {
    id: 'customize-42',
    artist: 'customize',
    name: "OH 5",
    src: "/audio/pro/customize/OH 5.mp3",
  },
  {
    id: 'customize-43',
    artist: 'customize',
    name: "OH 6",
    src: "/audio/pro/customize/OH 6.mp3",
  },
  {
    id: 'customize-44',
    artist: 'customize',
    name: "OH 7",
    src: "/audio/pro/customize/OH 7.mp3",
  },
  {
    id: 'customize-45',
    artist: 'customize',
    name: "Perc 1",
    src: "/audio/pro/customize/Perc 1.mp3",
  },
  {
    id: 'customize-46',
    artist: 'customize',
    name: "Perc 2",
    src: "/audio/pro/customize/Perc 2.mp3",
  },
  {
    id: 'customize-47',
    artist: 'customize',
    name: "Perc 3",
    src: "/audio/pro/customize/Perc 3.mp3",
  },
  {
    id: 'customize-48',
    artist: 'customize',
    name: "Perc 4",
    src: "/audio/pro/customize/Perc 4.mp3",
  },
  {
    id: 'customize-49',
    artist: 'customize',
    name: "Perc 5",
    src: "/audio/pro/customize/Perc 5.mp3",
  },
  {
    id: 'customize-50',
    artist: 'customize',
    name: "Perc 6",
    src: "/audio/pro/customize/Perc 6.mp3",
  },
  {
    id: 'customize-51',
    artist: 'customize',
    name: "Perc 7",
    src: "/audio/pro/customize/Perc 7.mp3",
  },
  {
    id: 'customize-52',
    artist: 'customize',
    name: "Perc 8",
    src: "/audio/pro/customize/Perc 8.mp3",
  },
  {
    id: 'customize-53',
    artist: 'customize',
    name: "Perc 9",
    src: "/audio/pro/customize/Perc 9.mp3",
  },
  {
    id: 'customize-54',
    artist: 'customize',
    name: "Perc 10",
    src: "/audio/pro/customize/Perc 10.mp3",
  },
  {
    id: 'customize-55',
    artist: 'customize',
    name: "Perc 11",
    src: "/audio/pro/customize/Perc 11.mp3",
  },
  {
    id: 'customize-56',
    artist: 'customize',
    name: "Perc 12",
    src: "/audio/pro/customize/Perc 12.mp3",
  },
  {
    id: 'customize-57',
    artist: 'customize',
    name: "Perc 13",
    src: "/audio/pro/customize/Perc 13.mp3",
  },
  {
    id: 'customize-58',
    artist: 'customize',
    name: "Perc 14",
    src: "/audio/pro/customize/Perc 14.mp3",
  },
  {
    id: 'customize-59',
    artist: 'customize',
    name: "Perc 15",
    src: "/audio/pro/customize/Perc 15.mp3",
  },
  {
    id: 'customize-60',
    artist: 'customize',
    name: "Perc 16",
    src: "/audio/pro/customize/Perc 16.mp3",
  },
  {
    id: 'customize-61',
    artist: 'customize',
    name: "Perc 17",
    src: "/audio/pro/customize/Perc 17.mp3",
  },
  {
    id: 'customize-62',
    artist: 'customize',
    name: "Perc 18",
    src: "/audio/pro/customize/Perc 18.mp3",
  },
  {
    id: 'customize-63',
    artist: 'customize',
    name: "Perc 19",
    src: "/audio/pro/customize/Perc 19.mp3",
  },
  {
    id: 'customize-64',
    artist: 'customize',
    name: "Perc 20",
    src: "/audio/pro/customize/Perc 20.mp3",
  },
  {
    id: 'customize-65',
    artist: 'customize',
    name: "Perc 21",
    src: "/audio/pro/customize/Perc 21.mp3",
  },
  {
    id: 'customize-66',
    artist: 'customize',
    name: "Snare 1",
    src: "/audio/pro/customize/Snare 1.mp3",
  },
  {
    id: 'customize-67',
    artist: 'customize',
    name: "Snare 2",
    src: "/audio/pro/customize/Snare 2.mp3",
  },
  {
    id: 'customize-68',
    artist: 'customize',
    name: "Snare 3",
    src: "/audio/pro/customize/Snare 3.mp3",
  },
  {
    id: 'customize-69',
    artist: 'customize',
    name: "Snare 4",
    src: "/audio/pro/customize/Snare 4.mp3",
  },
  {
    id: 'customize-70',
    artist: 'customize',
    name: "Snare 5",
    src: "/audio/pro/customize/Snare 5.mp3",
  },
  {
    id: 'customize-71',
    artist: 'customize',
    name: "Snare 6",
    src: "/audio/pro/customize/Snare 6.mp3",
  },
  {
    id: 'customize-72',
    artist: 'customize',
    name: "Snare 7",
    src: "/audio/pro/customize/Snare 7.mp3",
  },
  {
    id: 'customize-73',
    artist: 'customize',
    name: "Tom 1",
    src: "/audio/pro/customize/Tom 1.mp3",
  },
  {
    id: 'customize-74',
    artist: 'customize',
    name: "Tom 2",
    src: "/audio/pro/customize/Tom 2.mp3",
  },
  {
    id: 'customize-75',
    artist: 'customize',
    name: "Tom 3",
    src: "/audio/pro/customize/Tom 3.mp3",
  },
  {
    id: 'customize-76',
    artist: 'customize',
    name: "Tom 4",
    src: "/audio/pro/customize/Tom 4.mp3",
  },
  {
    id: 'customize-77',
    artist: 'customize',
    name: "Tom 5",
    src: "/audio/pro/customize/Tom 5.mp3",
  },
  {
    id: 'customize-78',
    artist: 'customize',
    name: "Tom 6",
    src: "/audio/pro/customize/Tom 6.mp3",
  },
  {
    id: 'customize-79',
    artist: 'customize',
    name: "Tom 7",
    src: "/audio/pro/customize/Tom 7.mp3",
  },
  {
    id: 'customize-80',
    artist: 'customize',
    name: "Tom 8",
    src: "/audio/pro/customize/Tom 8.mp3",
  },
  {
    id: 'customize-81',
    artist: 'customize',
    name: "Tom 9",
    src: "/audio/pro/customize/Tom 9.mp3",
  },
  {
    id: 'puzzleman-1',
    artist: 'puzzleman',
    name: "1 Kick 4-1",
    src: "/audio/pro/puzzleman/1 Kick 4-1-a.mp3",
  },
  {
    id: 'puzzleman-2',
    artist: 'puzzleman',
    name: "2 Snare 4-1",
    src: "/audio/pro/puzzleman/2 Snare 4-1-a.mp3",
  },
  {
    id: 'puzzleman-3',
    artist: 'puzzleman',
    name: "3 HH 4-1",
    src: "/audio/pro/puzzleman/3 HH 4-1-a.mp3",
  },
  {
    id: 'puzzleman-4',
    artist: 'puzzleman',
    name: "4 OH 4-1",
    src: "/audio/pro/puzzleman/4 OH 4-1-a.mp3",
  },
  {
    id: 'puzzleman-5',
    artist: 'puzzleman',
    name: "5 Clav 4-1",
    src: "/audio/pro/puzzleman/5 Clav 4-1.mp3",
  },
  {
    id: 'puzzleman-6',
    artist: 'puzzleman',
    name: "6 Congo 4-1",
    src: "/audio/pro/puzzleman/6 Congo 4-1.mp3",
  },
  {
    id: 'puzzleman-7',
    artist: 'puzzleman',
    name: "7 Congo 4-2",
    src: "/audio/pro/puzzleman/7 Congo 4-2.mp3",
  },
  {
    id: 'puzzleman-8',
    artist: 'puzzleman',
    name: "8 Tp 4-1",
    src: "/audio/pro/puzzleman/8 Tp 4-1.mp3",
  },
  {
    id: 'puzzleman-9',
    artist: 'puzzleman',
    name: "1 Kick 2-1",
    src: "/audio/pro/puzzleman/1 Kick 2-1.mp3",
  },
  {
    id: 'puzzleman-10',
    artist: 'puzzleman',
    name: "2 Snare 2-1",
    src: "/audio/pro/puzzleman/2 Snare 2-1.mp3",
  },
  {
    id: 'puzzleman-11',
    artist: 'puzzleman',
    name: "3 OH 2-1",
    src: "/audio/pro/puzzleman/3 OH 2-1.mp3",
  },
  {
    id: 'puzzleman-12',
    artist: 'puzzleman',
    name: "4 HH 2-1",
    src: "/audio/pro/puzzleman/4 HH 2-1.mp3",
  },
  {
    id: 'puzzleman-13',
    artist: 'puzzleman',
    name: "5 A# 2-1",
    src: "/audio/pro/puzzleman/5 A^ 2-1.mp3",
  },
  {
    id: 'puzzleman-14',
    artist: 'puzzleman',
    name: "6 C 2-1",
    src: "/audio/pro/puzzleman/6 C 2-1.mp3",
  },
  {
    id: 'puzzleman-15',
    artist: 'puzzleman',
    name: "7 F 2-1",
    src: "/audio/pro/puzzleman/7 F 2-1.mp3",
  },
  {
    id: 'puzzleman-16',
    artist: 'puzzleman',
    name: "8 G 2-1",
    src: "/audio/pro/puzzleman/8 G 2-1.mp3",
  },
  {
    id: 'puzzleman-17',
    artist: 'puzzleman',
    name: "1 Kick 3-1",
    src: "/audio/pro/puzzleman/1 Kick 3-1.mp3",
  },
  {
    id: 'puzzleman-18',
    artist: 'puzzleman',
    name: "2 Snare 3-1",
    src: "/audio/pro/puzzleman/2 Snare 3-1.mp3",
  },
  {
    id: 'puzzleman-19',
    artist: 'puzzleman',
    name: "3 HH 3-1",
    src: "/audio/pro/puzzleman/3 HH 3-1.mp3",
  },
  {
    id: 'puzzleman-20',
    artist: 'puzzleman',
    name: "4 HH 3-2",
    src: "/audio/pro/puzzleman/4 HH 3-2.mp3",
  },
  {
    id: 'puzzleman-21',
    artist: 'puzzleman',
    name: "5 Perc 3-1",
    src: "/audio/pro/puzzleman/5 Perc 3-1.mp3",
  },
  {
    id: 'puzzleman-22',
    artist: 'puzzleman',
    name: "6 Perc 3-2",
    src: "/audio/pro/puzzleman/6 Perc 3-2.mp3",
  },
  {
    id: 'puzzleman-23',
    artist: 'puzzleman',
    name: "7 Perc 3-3",
    src: "/audio/pro/puzzleman/7 Perc 3-3.mp3",
  },
  {
    id: 'puzzleman-24',
    artist: 'puzzleman',
    name: "8 Ride 3-1",
    src: "/audio/pro/puzzleman/8 Ride 3-1.mp3",
  },
  {
    id: 'puzzleman-25',
    artist: 'puzzleman',
    name: "1 Kick 4-1",
    src: "/audio/pro/puzzleman/1 Kick 4-1-b.mp3",
  },
  {
    id: 'puzzleman-26',
    artist: 'puzzleman',
    name: "2 Snare 4-1",
    src: "/audio/pro/puzzleman/2 Snare 4-1-b.mp3",
  },
  {
    id: 'puzzleman-27',
    artist: 'puzzleman',
    name: "3 HH 4-1",
    src: "/audio/pro/puzzleman/3 HH 4-1-b.mp3",
  },
  {
    id: 'puzzleman-28',
    artist: 'puzzleman',
    name: "4 OH 4-1",
    src: "/audio/pro/puzzleman/4 OH 4-1-b.mp3",
  },
  {
    id: 'puzzleman-29',
    artist: 'puzzleman',
    name: "5 Blochi 4-1",
    src: "/audio/pro/puzzleman/5 Blochi 4-1.mp3",
  },
  {
    id: 'puzzleman-30',
    artist: 'puzzleman',
    name: "6 Clow 4-1",
    src: "/audio/pro/puzzleman/6 Clow 4-1.mp3",
  },
  {
    id: 'puzzleman-31',
    artist: 'puzzleman',
    name: "7 Sk 4-1",
    src: "/audio/pro/puzzleman/7 Sk 4-1.mp3",
  },
  {
    id: 'puzzleman-32',
    artist: 'puzzleman',
    name: "8 Tamb 4-1",
    src: "/audio/pro/puzzleman/8 Tamb 4-1.mp3",
  },
  {
    id: 'puzzleman-33',
    artist: 'puzzleman',
    name: "A# 2-1",
    src: "/audio/pro/puzzleman/A^ 2-1.mp3",
  },
  {
    id: 'puzzleman-34',
    artist: 'puzzleman',
    name: "AG 2-1",
    src: "/audio/pro/puzzleman/AG 2-1.mp3",
  },
  {
    id: 'puzzleman-35',
    artist: 'puzzleman',
    name: "AG 2-2",
    src: "/audio/pro/puzzleman/AG 2-2.mp3",
  },
  {
    id: 'puzzleman-36',
    artist: 'puzzleman',
    name: "Bass C 1-1",
    src: "/audio/pro/puzzleman/Bass C 1-1.mp3",
  },
  {
    id: 'puzzleman-37',
    artist: 'puzzleman',
    name: "Bass C 3-2",
    src: "/audio/pro/puzzleman/Bass C 3-2.mp3",
  },
  {
    id: 'puzzleman-38',
    artist: 'puzzleman',
    name: "Bass F",
    src: "/audio/pro/puzzleman/Bass F.mp3",
  },
  {
    id: 'puzzleman-39',
    artist: 'puzzleman',
    name: "Bass G 1-1",
    src: "/audio/pro/puzzleman/Bass G 1-1.mp3",
  },
  {
    id: 'puzzleman-40',
    artist: 'puzzleman',
    name: "Bass G 4-1",
    src: "/audio/pro/puzzleman/Bass G 4-1.mp3",
  },
  {
    id: 'puzzleman-41',
    artist: 'puzzleman',
    name: "Bass G# 4-1",
    src: "/audio/pro/puzzleman/Bass G^ 4-1.mp3",
  },
  {
    id: 'puzzleman-42',
    artist: 'puzzleman',
    name: "Brass",
    src: "/audio/pro/puzzleman/Brass.mp3",
  },
  {
    id: 'puzzleman-43',
    artist: 'puzzleman',
    name: "C 2-1",
    src: "/audio/pro/puzzleman/C 2-1.mp3",
  },
  {
    id: 'puzzleman-44',
    artist: 'puzzleman',
    name: "Chord 1-1",
    src: "/audio/pro/puzzleman/Chord 1-1.mp3",
  },
  {
    id: 'puzzleman-45',
    artist: 'puzzleman',
    name: "Chord 1-2",
    src: "/audio/pro/puzzleman/Chord 1-2.mp3",
  },
  {
    id: 'puzzleman-46',
    artist: 'puzzleman',
    name: "Chord 1-3",
    src: "/audio/pro/puzzleman/Chord 1-3.mp3",
  },
  {
    id: 'puzzleman-47',
    artist: 'puzzleman',
    name: "Chord 3-3",
    src: "/audio/pro/puzzleman/Chord 3-3.mp3",
  },
  {
    id: 'puzzleman-48',
    artist: 'puzzleman',
    name: "Chord 3-4",
    src: "/audio/pro/puzzleman/Chord 3-4.mp3",
  },
  {
    id: 'puzzleman-49',
    artist: 'puzzleman',
    name: "Chord 3-5",
    src: "/audio/pro/puzzleman/Chord 3-5.mp3",
  },
  {
    id: 'puzzleman-50',
    artist: 'puzzleman',
    name: "EG 4-1",
    src: "/audio/pro/puzzleman/EG 4-1.mp3",
  },
  {
    id: 'puzzleman-51',
    artist: 'puzzleman',
    name: "EG 4-2",
    src: "/audio/pro/puzzleman/EG 4-2.mp3",
  },
  {
    id: 'puzzleman-52',
    artist: 'puzzleman',
    name: "F 2-1",
    src: "/audio/pro/puzzleman/F 2-1.mp3",
  },
  {
    id: 'puzzleman-53',
    artist: 'puzzleman',
    name: "G 2-1",
    src: "/audio/pro/puzzleman/G 2-1.mp3",
  },
  {
    id: 'puzzleman-54',
    artist: 'puzzleman',
    name: "Key A# 1-1",
    src: "/audio/pro/puzzleman/Key A^ 1-1.mp3",
  },
  {
    id: 'puzzleman-55',
    artist: 'puzzleman',
    name: "Key C 1-1",
    src: "/audio/pro/puzzleman/Key C 1-1.mp3",
  },
  {
    id: 'puzzleman-56',
    artist: 'puzzleman',
    name: "Key D# 1-1",
    src: "/audio/pro/puzzleman/Key D^ 1-1.mp3",
  },
  {
    id: 'puzzleman-57',
    artist: 'puzzleman',
    name: "Key F 1-1",
    src: "/audio/pro/puzzleman/Key F 1-1.mp3",
  },
  {
    id: 'puzzleman-58',
    artist: 'puzzleman',
    name: "Lead A# 4-1",
    src: "/audio/pro/puzzleman/Lead A^ 4-1.mp3",
  },
  {
    id: 'puzzleman-59',
    artist: 'puzzleman',
    name: "Lead C 4-1",
    src: "/audio/pro/puzzleman/Lead C 4-1.mp3",
  },
  {
    id: 'puzzleman-60',
    artist: 'puzzleman',
    name: "Lead D# 4-1",
    src: "/audio/pro/puzzleman/Lead D^ 4-1.mp3",
  },
  {
    id: 'puzzleman-61',
    artist: 'puzzleman',
    name: "Lead F 4-1",
    src: "/audio/pro/puzzleman/Lead F 4-1.mp3",
  },
  {
    id: 'puzzleman-62',
    artist: 'puzzleman',
    name: "Lead G 4-1",
    src: "/audio/pro/puzzleman/Lead G 4-1.mp3",
  },
  {
    id: 'puzzleman-63',
    artist: 'puzzleman',
    name: "Sax A# 3-1",
    src: "/audio/pro/puzzleman/Sax A^ 3-1.mp3",
  },
  {
    id: 'puzzleman-64',
    artist: 'puzzleman',
    name: "Sax C 3-1",
    src: "/audio/pro/puzzleman/Sax C 3-1.mp3",
  },
  {
    id: 'puzzleman-65',
    artist: 'puzzleman',
    name: "Sax D 3-1",
    src: "/audio/pro/puzzleman/Sax D 3-1.mp3",
  },
  {
    id: 'puzzleman-66',
    artist: 'puzzleman',
    name: "Sax D# 3-1",
    src: "/audio/pro/puzzleman/Sax D^ 3-1.mp3",
  },
  {
    id: 'puzzleman-67',
    artist: 'puzzleman',
    name: "Sax G 3-1",
    src: "/audio/pro/puzzleman/Sax G 3-1.mp3",
  },
];

export default proSamples;
