const proSamples = [
  {
    id: 'customize-1',
    artist: 'customize',
    name: "808 1 B",
    src: "/audio/pro/customize/808 1 B.mp3",
  },
  {
    id: 'customize-2',
    artist: 'customize',
    name: "808 1 E",
    src: "/audio/pro/customize/808 1 E.mp3",
  },
  {
    id: 'customize-3',
    artist: 'customize',
    name: "808 2 D",
    src: "/audio/pro/customize/808 2 D.mp3",
  },
  {
    id: 'customize-4',
    artist: 'customize',
    name: "808 2 E",
    src: "/audio/pro/customize/808 2 E.mp3",
  },
  {
    id: 'customize-5',
    artist: 'customize',
    name: "808 3 C",
    src: "/audio/pro/customize/808 3 C.mp3",
  },
  {
    id: 'customize-6',
    artist: 'customize',
    name: "808 3 E",
    src: "/audio/pro/customize/808 3 E.mp3",
  },
  {
    id: 'customize-7',
    artist: 'customize',
    name: "808 4 C",
    src: "/audio/pro/customize/808 4 C.mp3",
  },
  {
    id: 'customize-8',
    artist: 'customize',
    name: "808 5 B",
    src: "/audio/pro/customize/808 5 B.mp3",
  },
  {
    id: 'customize-9',
    artist: 'customize',
    name: "Bass B",
    src: "/audio/pro/customize/Bass B.mp3",
  },
  {
    id: 'customize-10',
    artist: 'customize',
    name: "Clap 1",
    src: "/audio/pro/customize/Clap 1.mp3",
  },
  {
    id: 'customize-11',
    artist: 'customize',
    name: "Clap 2",
    src: "/audio/pro/customize/Clap 2.mp3",
  },
  {
    id: 'customize-12',
    artist: 'customize',
    name: "Clap 3",
    src: "/audio/pro/customize/Clap 3.mp3",
  },
  {
    id: 'customize-13',
    artist: 'customize',
    name: "Clap 4",
    src: "/audio/pro/customize/Clap 4.mp3",
  },
  {
    id: 'customize-14',
    artist: 'customize',
    name: "Clap 5",
    src: "/audio/pro/customize/Clap 5.mp3",
  },
  {
    id: 'customize-15',
    artist: 'customize',
    name: "Crash 1",
    src: "/audio/pro/customize/Crash 1.mp3",
  },
  {
    id: 'customize-16',
    artist: 'customize',
    name: "Crash 2",
    src: "/audio/pro/customize/Crash 2.mp3",
  },
  {
    id: 'customize-17',
    artist: 'customize',
    name: "Crash1",
    src: "/audio/pro/customize/Crash1.mp3",
  },
  {
    id: 'customize-18',
    artist: 'customize',
    name: "Fx 1",
    src: "/audio/pro/customize/Fx 1.mp3",
  },
  {
    id: 'customize-19',
    artist: 'customize',
    name: "Fx 2",
    src: "/audio/pro/customize/Fx 2.mp3",
  },
  {
    id: 'customize-20',
    artist: 'customize',
    name: "Fx 3",
    src: "/audio/pro/customize/Fx 3.mp3",
  },
  {
    id: 'customize-21',
    artist: 'customize',
    name: "Fx 4",
    src: "/audio/pro/customize/Fx 4.mp3",
  },
  {
    id: 'customize-22',
    artist: 'customize',
    name: "HH 1",
    src: "/audio/pro/customize/HH 1.mp3",
  },
  {
    id: 'customize-23',
    artist: 'customize',
    name: "HH 2",
    src: "/audio/pro/customize/HH 2.mp3",
  },
  {
    id: 'customize-24',
    artist: 'customize',
    name: "HH 3",
    src: "/audio/pro/customize/HH 3.mp3",
  },
  {
    id: 'customize-25',
    artist: 'customize',
    name: "HH 4",
    src: "/audio/pro/customize/HH 4.mp3",
  },
  {
    id: 'customize-26',
    artist: 'customize',
    name: "HH 5",
    src: "/audio/pro/customize/HH 5.mp3",
  },
  {
    id: 'customize-27',
    artist: 'customize',
    name: "HH 6",
    src: "/audio/pro/customize/HH 6.mp3",
  },
  {
    id: 'customize-28',
    artist: 'customize',
    name: "HH 7",
    src: "/audio/pro/customize/HH 7.mp3",
  },
  {
    id: 'customize-29',
    artist: 'customize',
    name: "HH 8",
    src: "/audio/pro/customize/HH 8.mp3",
  },
  {
    id: 'customize-30',
    artist: 'customize',
    name: "HH 9",
    src: "/audio/pro/customize/HH 9.mp3",
  },
  {
    id: 'customize-31',
    artist: 'customize',
    name: "Kick 1",
    src: "/audio/pro/customize/Kick 1.mp3",
  },
  {
    id: 'customize-32',
    artist: 'customize',
    name: "Kick 2",
    src: "/audio/pro/customize/Kick 2.mp3",
  },
  {
    id: 'customize-33',
    artist: 'customize',
    name: "Kick 3",
    src: "/audio/pro/customize/Kick 3.mp3",
  },
  {
    id: 'customize-34',
    artist: 'customize',
    name: "Kick 4",
    src: "/audio/pro/customize/Kick 4.mp3",
  },
  {
    id: 'customize-35',
    artist: 'customize',
    name: "Kick 5",
    src: "/audio/pro/customize/Kick 5.mp3",
  },
  {
    id: 'customize-36',
    artist: 'customize',
    name: "Kick 6",
    src: "/audio/pro/customize/Kick 6.mp3",
  },
  {
    id: 'customize-37',
    artist: 'customize',
    name: "Kick 7",
    src: "/audio/pro/customize/Kick 7.mp3",
  },
  {
    id: 'customize-38',
    artist: 'customize',
    name: "OH 1",
    src: "/audio/pro/customize/OH 1.mp3",
  },
  {
    id: 'customize-39',
    artist: 'customize',
    name: "OH 2",
    src: "/audio/pro/customize/OH 2.mp3",
  },
  {
    id: 'customize-40',
    artist: 'customize',
    name: "OH 3",
    src: "/audio/pro/customize/OH 3.mp3",
  },
  {
    id: 'customize-41',
    artist: 'customize',
    name: "OH 4",
    src: "/audio/pro/customize/OH 4.mp3",
  },
  {
    id: 'customize-42',
    artist: 'customize',
    name: "OH 5",
    src: "/audio/pro/customize/OH 5.mp3",
  },
  {
    id: 'customize-43',
    artist: 'customize',
    name: "OH 6",
    src: "/audio/pro/customize/OH 6.mp3",
  },
  {
    id: 'customize-44',
    artist: 'customize',
    name: "OH 7",
    src: "/audio/pro/customize/OH 7.mp3",
  },
  {
    id: 'customize-45',
    artist: 'customize',
    name: "Perc 1",
    src: "/audio/pro/customize/Perc 1.mp3",
  },
  {
    id: 'customize-46',
    artist: 'customize',
    name: "Perc 2",
    src: "/audio/pro/customize/Perc 2.mp3",
  },
  {
    id: 'customize-47',
    artist: 'customize',
    name: "Perc 3",
    src: "/audio/pro/customize/Perc 3.mp3",
  },
  {
    id: 'customize-48',
    artist: 'customize',
    name: "Perc 4",
    src: "/audio/pro/customize/Perc 4.mp3",
  },
  {
    id: 'customize-49',
    artist: 'customize',
    name: "Perc 5",
    src: "/audio/pro/customize/Perc 5.mp3",
  },
  {
    id: 'customize-50',
    artist: 'customize',
    name: "Perc 6",
    src: "/audio/pro/customize/Perc 6.mp3",
  },
  {
    id: 'customize-51',
    artist: 'customize',
    name: "Perc 7",
    src: "/audio/pro/customize/Perc 7.mp3",
  },
  {
    id: 'customize-52',
    artist: 'customize',
    name: "Perc 8",
    src: "/audio/pro/customize/Perc 8.mp3",
  },
  {
    id: 'customize-53',
    artist: 'customize',
    name: "Perc 9",
    src: "/audio/pro/customize/Perc 9.mp3",
  },
  {
    id: 'customize-54',
    artist: 'customize',
    name: "Perc 10",
    src: "/audio/pro/customize/Perc 10.mp3",
  },
  {
    id: 'customize-55',
    artist: 'customize',
    name: "Perc 11",
    src: "/audio/pro/customize/Perc 11.mp3",
  },
  {
    id: 'customize-56',
    artist: 'customize',
    name: "Perc 12",
    src: "/audio/pro/customize/Perc 12.mp3",
  },
  {
    id: 'customize-57',
    artist: 'customize',
    name: "Perc 13",
    src: "/audio/pro/customize/Perc 13.mp3",
  },
  {
    id: 'customize-58',
    artist: 'customize',
    name: "Perc 14",
    src: "/audio/pro/customize/Perc 14.mp3",
  },
  {
    id: 'customize-59',
    artist: 'customize',
    name: "Perc 15",
    src: "/audio/pro/customize/Perc 15.mp3",
  },
  {
    id: 'customize-60',
    artist: 'customize',
    name: "Perc 16",
    src: "/audio/pro/customize/Perc 16.mp3",
  },
  {
    id: 'customize-61',
    artist: 'customize',
    name: "Perc 17",
    src: "/audio/pro/customize/Perc 17.mp3",
  },
  {
    id: 'customize-62',
    artist: 'customize',
    name: "Perc 18",
    src: "/audio/pro/customize/Perc 18.mp3",
  },
  {
    id: 'customize-63',
    artist: 'customize',
    name: "Perc 19",
    src: "/audio/pro/customize/Perc 19.mp3",
  },
  {
    id: 'customize-64',
    artist: 'customize',
    name: "Perc 20",
    src: "/audio/pro/customize/Perc 20.mp3",
  },
  {
    id: 'customize-65',
    artist: 'customize',
    name: "Perc 21",
    src: "/audio/pro/customize/Perc 21.mp3",
  },
  {
    id: 'customize-66',
    artist: 'customize',
    name: "Snare 1",
    src: "/audio/pro/customize/Snare 1.mp3",
  },
  {
    id: 'customize-67',
    artist: 'customize',
    name: "Snare 2",
    src: "/audio/pro/customize/Snare 2.mp3",
  },
  {
    id: 'customize-68',
    artist: 'customize',
    name: "Snare 3",
    src: "/audio/pro/customize/Snare 3.mp3",
  },
  {
    id: 'customize-69',
    artist: 'customize',
    name: "Snare 4",
    src: "/audio/pro/customize/Snare 4.mp3",
  },
  {
    id: 'customize-70',
    artist: 'customize',
    name: "Snare 5",
    src: "/audio/pro/customize/Snare 5.mp3",
  },
  {
    id: 'customize-71',
    artist: 'customize',
    name: "Snare 6",
    src: "/audio/pro/customize/Snare 6.mp3",
  },
  {
    id: 'customize-72',
    artist: 'customize',
    name: "Snare 7",
    src: "/audio/pro/customize/Snare 7.mp3",
  },
  {
    id: 'customize-73',
    artist: 'customize',
    name: "Tom 1",
    src: "/audio/pro/customize/Tom 1.mp3",
  },
  {
    id: 'customize-74',
    artist: 'customize',
    name: "Tom 2",
    src: "/audio/pro/customize/Tom 2.mp3",
  },
  {
    id: 'customize-75',
    artist: 'customize',
    name: "Tom 3",
    src: "/audio/pro/customize/Tom 3.mp3",
  },
  {
    id: 'customize-76',
    artist: 'customize',
    name: "Tom 4",
    src: "/audio/pro/customize/Tom 4.mp3",
  },
  {
    id: 'customize-77',
    artist: 'customize',
    name: "Tom 5",
    src: "/audio/pro/customize/Tom 5.mp3",
  },
  {
    id: 'customize-78',
    artist: 'customize',
    name: "Tom 6",
    src: "/audio/pro/customize/Tom 6.mp3",
  },
  {
    id: 'customize-79',
    artist: 'customize',
    name: "Tom 7",
    src: "/audio/pro/customize/Tom 7.mp3",
  },
  {
    id: 'customize-80',
    artist: 'customize',
    name: "Tom 8",
    src: "/audio/pro/customize/Tom 8.mp3",
  },
  {
    id: 'customize-81',
    artist: 'customize',
    name: "Tom 9",
    src: "/audio/pro/customize/Tom 9.mp3",
  },
  {
    id: 'puzzleman-1',
    artist: 'puzzleman',
    name: "1 Kick 4-1",
    src: "/audio/pro/puzzleman/1 Kick 4-1-a.mp3",
  },
  {
    id: 'puzzleman-2',
    artist: 'puzzleman',
    name: "2 Snare 4-1",
    src: "/audio/pro/puzzleman/2 Snare 4-1-a.mp3",
  },
  {
    id: 'puzzleman-3',
    artist: 'puzzleman',
    name: "3 HH 4-1",
    src: "/audio/pro/puzzleman/3 HH 4-1-a.mp3",
  },
  {
    id: 'puzzleman-4',
    artist: 'puzzleman',
    name: "4 OH 4-1",
    src: "/audio/pro/puzzleman/4 OH 4-1-a.mp3",
  },
  {
    id: 'puzzleman-5',
    artist: 'puzzleman',
    name: "5 Clav 4-1",
    src: "/audio/pro/puzzleman/5 Clav 4-1.mp3",
  },
  {
    id: 'puzzleman-6',
    artist: 'puzzleman',
    name: "6 Congo 4-1",
    src: "/audio/pro/puzzleman/6 Congo 4-1.mp3",
  },
  {
    id: 'puzzleman-7',
    artist: 'puzzleman',
    name: "7 Congo 4-2",
    src: "/audio/pro/puzzleman/7 Congo 4-2.mp3",
  },
  {
    id: 'puzzleman-8',
    artist: 'puzzleman',
    name: "8 Tp 4-1",
    src: "/audio/pro/puzzleman/8 Tp 4-1.mp3",
  },
  {
    id: 'puzzleman-9',
    artist: 'puzzleman',
    name: "1 Kick 2-1",
    src: "/audio/pro/puzzleman/1 Kick 2-1.mp3",
  },
  {
    id: 'puzzleman-10',
    artist: 'puzzleman',
    name: "2 Snare 2-1",
    src: "/audio/pro/puzzleman/2 Snare 2-1.mp3",
  },
  {
    id: 'puzzleman-11',
    artist: 'puzzleman',
    name: "3 OH 2-1",
    src: "/audio/pro/puzzleman/3 OH 2-1.mp3",
  },
  {
    id: 'puzzleman-12',
    artist: 'puzzleman',
    name: "4 HH 2-1",
    src: "/audio/pro/puzzleman/4 HH 2-1.mp3",
  },
  {
    id: 'puzzleman-13',
    artist: 'puzzleman',
    name: "5 A# 2-1",
    src: "/audio/pro/puzzleman/5 A^ 2-1.mp3",
  },
  {
    id: 'puzzleman-14',
    artist: 'puzzleman',
    name: "6 C 2-1",
    src: "/audio/pro/puzzleman/6 C 2-1.mp3",
  },
  {
    id: 'puzzleman-15',
    artist: 'puzzleman',
    name: "7 F 2-1",
    src: "/audio/pro/puzzleman/7 F 2-1.mp3",
  },
  {
    id: 'puzzleman-16',
    artist: 'puzzleman',
    name: "8 G 2-1",
    src: "/audio/pro/puzzleman/8 G 2-1.mp3",
  },
  {
    id: 'puzzleman-17',
    artist: 'puzzleman',
    name: "1 Kick 3-1",
    src: "/audio/pro/puzzleman/1 Kick 3-1.mp3",
  },
  {
    id: 'puzzleman-18',
    artist: 'puzzleman',
    name: "2 Snare 3-1",
    src: "/audio/pro/puzzleman/2 Snare 3-1.mp3",
  },
  {
    id: 'puzzleman-19',
    artist: 'puzzleman',
    name: "3 HH 3-1",
    src: "/audio/pro/puzzleman/3 HH 3-1.mp3",
  },
  {
    id: 'puzzleman-20',
    artist: 'puzzleman',
    name: "4 HH 3-2",
    src: "/audio/pro/puzzleman/4 HH 3-2.mp3",
  },
  {
    id: 'puzzleman-21',
    artist: 'puzzleman',
    name: "5 Perc 3-1",
    src: "/audio/pro/puzzleman/5 Perc 3-1.mp3",
  },
  {
    id: 'puzzleman-22',
    artist: 'puzzleman',
    name: "6 Perc 3-2",
    src: "/audio/pro/puzzleman/6 Perc 3-2.mp3",
  },
  {
    id: 'puzzleman-23',
    artist: 'puzzleman',
    name: "7 Perc 3-3",
    src: "/audio/pro/puzzleman/7 Perc 3-3.mp3",
  },
  {
    id: 'puzzleman-24',
    artist: 'puzzleman',
    name: "8 Ride 3-1",
    src: "/audio/pro/puzzleman/8 Ride 3-1.mp3",
  },
  {
    id: 'puzzleman-25',
    artist: 'puzzleman',
    name: "1 Kick 4-1",
    src: "/audio/pro/puzzleman/1 Kick 4-1-b.mp3",
  },
  {
    id: 'puzzleman-26',
    artist: 'puzzleman',
    name: "2 Snare 4-1",
    src: "/audio/pro/puzzleman/2 Snare 4-1-b.mp3",
  },
  {
    id: 'puzzleman-27',
    artist: 'puzzleman',
    name: "3 HH 4-1",
    src: "/audio/pro/puzzleman/3 HH 4-1-b.mp3",
  },
  {
    id: 'puzzleman-28',
    artist: 'puzzleman',
    name: "4 OH 4-1",
    src: "/audio/pro/puzzleman/4 OH 4-1-b.mp3",
  },
  {
    id: 'puzzleman-29',
    artist: 'puzzleman',
    name: "5 Blochi 4-1",
    src: "/audio/pro/puzzleman/5 Blochi 4-1.mp3",
  },
  {
    id: 'puzzleman-30',
    artist: 'puzzleman',
    name: "6 Clow 4-1",
    src: "/audio/pro/puzzleman/6 Clow 4-1.mp3",
  },
  {
    id: 'puzzleman-31',
    artist: 'puzzleman',
    name: "7 Sk 4-1",
    src: "/audio/pro/puzzleman/7 Sk 4-1.mp3",
  },
  {
    id: 'puzzleman-32',
    artist: 'puzzleman',
    name: "8 Tamb 4-1",
    src: "/audio/pro/puzzleman/8 Tamb 4-1.mp3",
  },
  {
    id: 'puzzleman-33',
    artist: 'puzzleman',
    name: "A# 2-1",
    src: "/audio/pro/puzzleman/A^ 2-1.mp3",
  },
  {
    id: 'puzzleman-34',
    artist: 'puzzleman',
    name: "AG 2-1",
    src: "/audio/pro/puzzleman/AG 2-1.mp3",
  },
  {
    id: 'puzzleman-35',
    artist: 'puzzleman',
    name: "AG 2-2",
    src: "/audio/pro/puzzleman/AG 2-2.mp3",
  },
  {
    id: 'puzzleman-36',
    artist: 'puzzleman',
    name: "Bass C 1-1",
    src: "/audio/pro/puzzleman/Bass C 1-1.mp3",
  },
  {
    id: 'puzzleman-37',
    artist: 'puzzleman',
    name: "Bass C 3-2",
    src: "/audio/pro/puzzleman/Bass C 3-2.mp3",
  },
  {
    id: 'puzzleman-38',
    artist: 'puzzleman',
    name: "Bass F",
    src: "/audio/pro/puzzleman/Bass F.mp3",
  },
  {
    id: 'puzzleman-39',
    artist: 'puzzleman',
    name: "Bass G 1-1",
    src: "/audio/pro/puzzleman/Bass G 1-1.mp3",
  },
  {
    id: 'puzzleman-40',
    artist: 'puzzleman',
    name: "Bass G 4-1",
    src: "/audio/pro/puzzleman/Bass G 4-1.mp3",
  },
  {
    id: 'puzzleman-41',
    artist: 'puzzleman',
    name: "Bass G# 4-1",
    src: "/audio/pro/puzzleman/Bass G^ 4-1.mp3",
  },
  {
    id: 'puzzleman-42',
    artist: 'puzzleman',
    name: "Brass",
    src: "/audio/pro/puzzleman/Brass.mp3",
  },
  {
    id: 'puzzleman-43',
    artist: 'puzzleman',
    name: "C 2-1",
    src: "/audio/pro/puzzleman/C 2-1.mp3",
  },
  {
    id: 'puzzleman-44',
    artist: 'puzzleman',
    name: "Chord 1-1",
    src: "/audio/pro/puzzleman/Chord 1-1.mp3",
  },
  {
    id: 'puzzleman-45',
    artist: 'puzzleman',
    name: "Chord 1-2",
    src: "/audio/pro/puzzleman/Chord 1-2.mp3",
  },
  {
    id: 'puzzleman-46',
    artist: 'puzzleman',
    name: "Chord 1-3",
    src: "/audio/pro/puzzleman/Chord 1-3.mp3",
  },
  {
    id: 'puzzleman-47',
    artist: 'puzzleman',
    name: "Chord 3-3",
    src: "/audio/pro/puzzleman/Chord 3-3.mp3",
  },
  {
    id: 'puzzleman-48',
    artist: 'puzzleman',
    name: "Chord 3-4",
    src: "/audio/pro/puzzleman/Chord 3-4.mp3",
  },
  {
    id: 'puzzleman-49',
    artist: 'puzzleman',
    name: "Chord 3-5",
    src: "/audio/pro/puzzleman/Chord 3-5.mp3",
  },
  {
    id: 'puzzleman-50',
    artist: 'puzzleman',
    name: "EG 4-1",
    src: "/audio/pro/puzzleman/EG 4-1.mp3",
  },
  {
    id: 'puzzleman-51',
    artist: 'puzzleman',
    name: "EG 4-2",
    src: "/audio/pro/puzzleman/EG 4-2.mp3",
  },
  {
    id: 'puzzleman-52',
    artist: 'puzzleman',
    name: "F 2-1",
    src: "/audio/pro/puzzleman/F 2-1.mp3",
  },
  {
    id: 'puzzleman-53',
    artist: 'puzzleman',
    name: "G 2-1",
    src: "/audio/pro/puzzleman/G 2-1.mp3",
  },
  {
    id: 'puzzleman-54',
    artist: 'puzzleman',
    name: "Key A# 1-1",
    src: "/audio/pro/puzzleman/Key A^ 1-1.mp3",
  },
  {
    id: 'puzzleman-55',
    artist: 'puzzleman',
    name: "Key C 1-1",
    src: "/audio/pro/puzzleman/Key C 1-1.mp3",
  },
  {
    id: 'puzzleman-56',
    artist: 'puzzleman',
    name: "Key D# 1-1",
    src: "/audio/pro/puzzleman/Key D^ 1-1.mp3",
  },
  {
    id: 'puzzleman-57',
    artist: 'puzzleman',
    name: "Key F 1-1",
    src: "/audio/pro/puzzleman/Key F 1-1.mp3",
  },
  {
    id: 'puzzleman-58',
    artist: 'puzzleman',
    name: "Lead A# 4-1",
    src: "/audio/pro/puzzleman/Lead A^ 4-1.mp3",
  },
  {
    id: 'puzzleman-59',
    artist: 'puzzleman',
    name: "Lead C 4-1",
    src: "/audio/pro/puzzleman/Lead C 4-1.mp3",
  },
  {
    id: 'puzzleman-60',
    artist: 'puzzleman',
    name: "Lead D# 4-1",
    src: "/audio/pro/puzzleman/Lead D^ 4-1.mp3",
  },
  {
    id: 'puzzleman-61',
    artist: 'puzzleman',
    name: "Lead F 4-1",
    src: "/audio/pro/puzzleman/Lead F 4-1.mp3",
  },
  {
    id: 'puzzleman-62',
    artist: 'puzzleman',
    name: "Lead G 4-1",
    src: "/audio/pro/puzzleman/Lead G 4-1.mp3",
  },
  {
    id: 'puzzleman-63',
    artist: 'puzzleman',
    name: "Sax A# 3-1",
    src: "/audio/pro/puzzleman/Sax A^ 3-1.mp3",
  },
  {
    id: 'puzzleman-64',
    artist: 'puzzleman',
    name: "Sax C 3-1",
    src: "/audio/pro/puzzleman/Sax C 3-1.mp3",
  },
  {
    id: 'puzzleman-65',
    artist: 'puzzleman',
    name: "Sax D 3-1",
    src: "/audio/pro/puzzleman/Sax D 3-1.mp3",
  },
  {
    id: 'puzzleman-66',
    artist: 'puzzleman',
    name: "Sax D# 3-1",
    src: "/audio/pro/puzzleman/Sax D^ 3-1.mp3",
  },
  {
    id: 'puzzleman-67',
    artist: 'puzzleman',
    name: "Sax G 3-1",
    src: "/audio/pro/puzzleman/Sax G 3-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-1',
    artist: 'sunset-rollercoaster',
    name: "1 EG 1-1",
    src: "/audio/pro/sunset-rollercoaster/1 EG 1-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-2',
    artist: 'sunset-rollercoaster',
    name: "2 EG 1-2",
    src: "/audio/pro/sunset-rollercoaster/2 EG 1-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-3',
    artist: 'sunset-rollercoaster',
    name: "3 EG 1-3",
    src: "/audio/pro/sunset-rollercoaster/3 EG 1-3.mp3",
  },
  {
    id: 'sunset-rollercoaster-4',
    artist: 'sunset-rollercoaster',
    name: "4 EG 1-4",
    src: "/audio/pro/sunset-rollercoaster/4 EG 1-4.mp3",
  },
  {
    id: 'sunset-rollercoaster-5',
    artist: 'sunset-rollercoaster',
    name: "5 EG 1-5",
    src: "/audio/pro/sunset-rollercoaster/5 EG 1-5.mp3",
  },
  {
    id: 'sunset-rollercoaster-6',
    artist: 'sunset-rollercoaster',
    name: "6 EG 1-6",
    src: "/audio/pro/sunset-rollercoaster/6 EG 1-6.mp3",
  },
  {
    id: 'sunset-rollercoaster-7',
    artist: 'sunset-rollercoaster',
    name: "7 EG 1-7",
    src: "/audio/pro/sunset-rollercoaster/7 EG 1-7.mp3",
  },
  {
    id: 'sunset-rollercoaster-8',
    artist: 'sunset-rollercoaster',
    name: "8 EG 1-8",
    src: "/audio/pro/sunset-rollercoaster/8 EG 1-8.mp3",
  },
  {
    id: 'sunset-rollercoaster-9',
    artist: 'sunset-rollercoaster',
    name: "1 ML 2-1",
    src: "/audio/pro/sunset-rollercoaster/1 ML 2-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-10',
    artist: 'sunset-rollercoaster',
    name: "2 ML 2-2",
    src: "/audio/pro/sunset-rollercoaster/2 ML 2-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-11',
    artist: 'sunset-rollercoaster',
    name: "3 ML 2-3",
    src: "/audio/pro/sunset-rollercoaster/3 ML 2-3.mp3",
  },
  {
    id: 'sunset-rollercoaster-12',
    artist: 'sunset-rollercoaster',
    name: "4 ML 2-4",
    src: "/audio/pro/sunset-rollercoaster/4 ML 2-4.mp3",
  },
  {
    id: 'sunset-rollercoaster-13',
    artist: 'sunset-rollercoaster',
    name: "5 ML 2-5",
    src: "/audio/pro/sunset-rollercoaster/5 ML 2-5.mp3",
  },
  {
    id: 'sunset-rollercoaster-14',
    artist: 'sunset-rollercoaster',
    name: "6 ML 2-6",
    src: "/audio/pro/sunset-rollercoaster/6 ML 2-6.mp3",
  },
  {
    id: 'sunset-rollercoaster-15',
    artist: 'sunset-rollercoaster',
    name: "7 ML 2-7",
    src: "/audio/pro/sunset-rollercoaster/7 ML 2-7.mp3",
  },
  {
    id: 'sunset-rollercoaster-16',
    artist: 'sunset-rollercoaster',
    name: "8 ML 2-8",
    src: "/audio/pro/sunset-rollercoaster/8 ML 2-8.mp3",
  },
  {
    id: 'sunset-rollercoaster-17',
    artist: 'sunset-rollercoaster',
    name: "1 Bass Bb 3-1",
    src: "/audio/pro/sunset-rollercoaster/1 Bass Bb 3-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-18',
    artist: 'sunset-rollercoaster',
    name: "2 Bass Bb 3-2",
    src: "/audio/pro/sunset-rollercoaster/2 Bass Bb 3-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-19',
    artist: 'sunset-rollercoaster',
    name: "3 Bass Bb 3-3",
    src: "/audio/pro/sunset-rollercoaster/3 Bass Bb 3-3.mp3",
  },
  {
    id: 'sunset-rollercoaster-20',
    artist: 'sunset-rollercoaster',
    name: "4 Bass C 3-1",
    src: "/audio/pro/sunset-rollercoaster/4 Bass C 3-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-21',
    artist: 'sunset-rollercoaster',
    name: "5 Bass C 3-2",
    src: "/audio/pro/sunset-rollercoaster/5 Bass C 3-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-22',
    artist: 'sunset-rollercoaster',
    name: "6 Bass C# 3-1",
    src: "/audio/pro/sunset-rollercoaster/6 Bass C^ 3-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-23',
    artist: 'sunset-rollercoaster',
    name: "7 Bass C# 3-2",
    src: "/audio/pro/sunset-rollercoaster/7 Bass C^ 3-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-24',
    artist: 'sunset-rollercoaster',
    name: "8 Bass Eb 3-1",
    src: "/audio/pro/sunset-rollercoaster/8 Bass Eb 3-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-25',
    artist: 'sunset-rollercoaster',
    name: "1 Pk 4-1",
    src: "/audio/pro/sunset-rollercoaster/1 Pk 4-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-26',
    artist: 'sunset-rollercoaster',
    name: "2 Pk 4-2",
    src: "/audio/pro/sunset-rollercoaster/2 Pk 4-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-27',
    artist: 'sunset-rollercoaster',
    name: "3 Pk 4-3",
    src: "/audio/pro/sunset-rollercoaster/3 Pk 4-3.mp3",
  },
  {
    id: 'sunset-rollercoaster-28',
    artist: 'sunset-rollercoaster',
    name: "4 Pk 4-4",
    src: "/audio/pro/sunset-rollercoaster/4 Pk 4-4.mp3",
  },
  {
    id: 'sunset-rollercoaster-29',
    artist: 'sunset-rollercoaster',
    name: "5 Pk 4-5",
    src: "/audio/pro/sunset-rollercoaster/5 Pk 4-5.mp3",
  },
  {
    id: 'sunset-rollercoaster-30',
    artist: 'sunset-rollercoaster',
    name: "6 Pk 4-6",
    src: "/audio/pro/sunset-rollercoaster/6 Pk 4-6.mp3",
  },
  {
    id: 'sunset-rollercoaster-31',
    artist: 'sunset-rollercoaster',
    name: "7 Pk 4-7",
    src: "/audio/pro/sunset-rollercoaster/7 Pk 4-7.mp3",
  },
  {
    id: 'sunset-rollercoaster-32',
    artist: 'sunset-rollercoaster',
    name: "8 Pk 4-8",
    src: "/audio/pro/sunset-rollercoaster/8 Pk 4-8.mp3",
  },
  {
    id: 'sunset-rollercoaster-33',
    artist: 'sunset-rollercoaster',
    name: "Bass F 3-1",
    src: "/audio/pro/sunset-rollercoaster/Bass F 3-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-34',
    artist: 'sunset-rollercoaster',
    name: "Bass F# 3-1",
    src: "/audio/pro/sunset-rollercoaster/Bass F^ 3-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-35',
    artist: 'sunset-rollercoaster',
    name: "Clap 1-1",
    src: "/audio/pro/sunset-rollercoaster/Clap 1-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-36',
    artist: 'sunset-rollercoaster',
    name: "EG 1-9",
    src: "/audio/pro/sunset-rollercoaster/EG 1-9.mp3",
  },
  {
    id: 'sunset-rollercoaster-37',
    artist: 'sunset-rollercoaster',
    name: "HH 1-1",
    src: "/audio/pro/sunset-rollercoaster/HH 1-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-38',
    artist: 'sunset-rollercoaster',
    name: "HH 1-2",
    src: "/audio/pro/sunset-rollercoaster/HH 1-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-39',
    artist: 'sunset-rollercoaster',
    name: "HH 1-3",
    src: "/audio/pro/sunset-rollercoaster/HH 1-3.mp3",
  },
  {
    id: 'sunset-rollercoaster-40',
    artist: 'sunset-rollercoaster',
    name: "Key 1-1",
    src: "/audio/pro/sunset-rollercoaster/Key 1-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-41',
    artist: 'sunset-rollercoaster',
    name: "Key 1-2",
    src: "/audio/pro/sunset-rollercoaster/Key 1-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-42',
    artist: 'sunset-rollercoaster',
    name: "Key 1-3",
    src: "/audio/pro/sunset-rollercoaster/Key 1-3.mp3",
  },
  {
    id: 'sunset-rollercoaster-43',
    artist: 'sunset-rollercoaster',
    name: "Kick 1-1",
    src: "/audio/pro/sunset-rollercoaster/Kick 1-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-44',
    artist: 'sunset-rollercoaster',
    name: "Kick 1-2",
    src: "/audio/pro/sunset-rollercoaster/Kick 1-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-45',
    artist: 'sunset-rollercoaster',
    name: "ML 1-10",
    src: "/audio/pro/sunset-rollercoaster/ML 1-10.mp3",
  },
  {
    id: 'sunset-rollercoaster-46',
    artist: 'sunset-rollercoaster',
    name: "ML 1-9",
    src: "/audio/pro/sunset-rollercoaster/ML 1-9.mp3",
  },
  {
    id: 'sunset-rollercoaster-47',
    artist: 'sunset-rollercoaster',
    name: "OH 1-4",
    src: "/audio/pro/sunset-rollercoaster/OH 1-4.mp3",
  },
  {
    id: 'sunset-rollercoaster-48',
    artist: 'sunset-rollercoaster',
    name: "Perc 1-1",
    src: "/audio/pro/sunset-rollercoaster/Perc 1-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-49',
    artist: 'sunset-rollercoaster',
    name: "Perc 1-2",
    src: "/audio/pro/sunset-rollercoaster/Perc 1-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-50',
    artist: 'sunset-rollercoaster',
    name: "Perc 1-3",
    src: "/audio/pro/sunset-rollercoaster/Perc 1-3.mp3",
  },
  {
    id: 'sunset-rollercoaster-51',
    artist: 'sunset-rollercoaster',
    name: "Pk 1-9",
    src: "/audio/pro/sunset-rollercoaster/Pk 1-9.mp3",
  },
  {
    id: 'sunset-rollercoaster-52',
    artist: 'sunset-rollercoaster',
    name: "Snare 1-1",
    src: "/audio/pro/sunset-rollercoaster/Snare 1-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-53',
    artist: 'sunset-rollercoaster',
    name: "Snare 1-2",
    src: "/audio/pro/sunset-rollercoaster/Snare 1-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-54',
    artist: 'sunset-rollercoaster',
    name: "Solo 1-1",
    src: "/audio/pro/sunset-rollercoaster/Solo 1-1.mp3",
  },
  {
    id: 'sunset-rollercoaster-55',
    artist: 'sunset-rollercoaster',
    name: "Solo 1-2",
    src: "/audio/pro/sunset-rollercoaster/Solo 1-2.mp3",
  },
  {
    id: 'sunset-rollercoaster-56',
    artist: 'sunset-rollercoaster',
    name: "Solo 1-3",
    src: "/audio/pro/sunset-rollercoaster/Solo 1-3.mp3",
  },
  {
    id: 'sunset-rollercoaster-57',
    artist: 'sunset-rollercoaster',
    name: "Solo 1-4",
    src: "/audio/pro/sunset-rollercoaster/Solo 1-4.mp3",
  },
  {
    id: 'enno-chunho-1',
    artist: 'enno-chunho',
    name: "1 Vocal 1-1",
    src: "/audio/pro/enno-chunho/1 Vocal 1-1.mp3",
  },
  {
    id: 'enno-chunho-2',
    artist: 'enno-chunho',
    name: "2 Vocal 1-2",
    src: "/audio/pro/enno-chunho/2 Vocal 1-2.mp3",
  },
  {
    id: 'enno-chunho-3',
    artist: 'enno-chunho',
    name: "3 Vocal 1-3",
    src: "/audio/pro/enno-chunho/3 Vocal 1-3.mp3",
  },
  {
    id: 'enno-chunho-4',
    artist: 'enno-chunho',
    name: "4 Vocal 1-4",
    src: "/audio/pro/enno-chunho/4 Vocal 1-4.mp3",
  },
  {
    id: 'enno-chunho-5',
    artist: 'enno-chunho',
    name: "5 Vocal 1-5",
    src: "/audio/pro/enno-chunho/5 Vocal 1-5.mp3",
  },
  {
    id: 'enno-chunho-6',
    artist: 'enno-chunho',
    name: "6 Vocal 1-6",
    src: "/audio/pro/enno-chunho/6 Vocal 1-6.mp3",
  },
  {
    id: 'enno-chunho-7',
    artist: 'enno-chunho',
    name: "7 Vocal 1-7",
    src: "/audio/pro/enno-chunho/7 Vocal 1-7.mp3",
  },
  {
    id: 'enno-chunho-8',
    artist: 'enno-chunho',
    name: "8 Vocal 1-8",
    src: "/audio/pro/enno-chunho/8 Vocal 1-8.mp3",
  },
  {
    id: 'enno-chunho-9',
    artist: 'enno-chunho',
    name: "1 Vocal 2-1",
    src: "/audio/pro/enno-chunho/1 Vocal 2-1.mp3",
  },
  {
    id: 'enno-chunho-10',
    artist: 'enno-chunho',
    name: "2 Vocal 2-2",
    src: "/audio/pro/enno-chunho/2 Vocal 2-2.mp3",
  },
  {
    id: 'enno-chunho-11',
    artist: 'enno-chunho',
    name: "3 Vocal 2-3",
    src: "/audio/pro/enno-chunho/3 Vocal 2-3.mp3",
  },
  {
    id: 'enno-chunho-12',
    artist: 'enno-chunho',
    name: "4 Vocal 2-4",
    src: "/audio/pro/enno-chunho/4 Vocal 2-4.mp3",
  },
  {
    id: 'enno-chunho-13',
    artist: 'enno-chunho',
    name: "5 Vocal 2-5",
    src: "/audio/pro/enno-chunho/5 Vocal 2-5.mp3",
  },
  {
    id: 'enno-chunho-14',
    artist: 'enno-chunho',
    name: "6 Vocal 2-6",
    src: "/audio/pro/enno-chunho/6 Vocal 2-6.mp3",
  },
  {
    id: 'enno-chunho-15',
    artist: 'enno-chunho',
    name: "7 Vocal 2-7",
    src: "/audio/pro/enno-chunho/7 Vocal 2-7.mp3",
  },
  {
    id: 'enno-chunho-16',
    artist: 'enno-chunho',
    name: "8 Vocal 2-8",
    src: "/audio/pro/enno-chunho/8 Vocal 2-8.mp3",
  },
  {
    id: 'enno-chunho-17',
    artist: 'enno-chunho',
    name: "1 Vocal 3-1",
    src: "/audio/pro/enno-chunho/1 Vocal 3-1.mp3",
  },
  {
    id: 'enno-chunho-18',
    artist: 'enno-chunho',
    name: "2 Vocal 3-2",
    src: "/audio/pro/enno-chunho/2 Vocal 3-2.mp3",
  },
  {
    id: 'enno-chunho-19',
    artist: 'enno-chunho',
    name: "3 Vocal 3-3",
    src: "/audio/pro/enno-chunho/3 Vocal 3-3.mp3",
  },
  {
    id: 'enno-chunho-20',
    artist: 'enno-chunho',
    name: "4 Vocal 3-4",
    src: "/audio/pro/enno-chunho/4 Vocal 3-4.mp3",
  },
  {
    id: 'enno-chunho-21',
    artist: 'enno-chunho',
    name: "5 Vocal 3-5",
    src: "/audio/pro/enno-chunho/5 Vocal 3-5.mp3",
  },
  {
    id: 'enno-chunho-22',
    artist: 'enno-chunho',
    name: "6 Vocal 3-6",
    src: "/audio/pro/enno-chunho/6 Vocal 3-6.mp3",
  },
  {
    id: 'enno-chunho-23',
    artist: 'enno-chunho',
    name: "7 Vocal 3-7",
    src: "/audio/pro/enno-chunho/7 Vocal 3-7.mp3",
  },
  {
    id: 'enno-chunho-24',
    artist: 'enno-chunho',
    name: "8 Vocal 3-8",
    src: "/audio/pro/enno-chunho/8 Vocal 3-8.mp3",
  },
  {
    id: 'enno-chunho-25',
    artist: 'enno-chunho',
    name: "1 Vocal 4-1",
    src: "/audio/pro/enno-chunho/1 Vocal 4-1.mp3",
  },
  {
    id: 'enno-chunho-26',
    artist: 'enno-chunho',
    name: "2 Vocal 4-2",
    src: "/audio/pro/enno-chunho/2 Vocal 4-2.mp3",
  },
  {
    id: 'enno-chunho-27',
    artist: 'enno-chunho',
    name: "3 Vocal 4-3",
    src: "/audio/pro/enno-chunho/3 Vocal 4-3.mp3",
  },
  {
    id: 'enno-chunho-28',
    artist: 'enno-chunho',
    name: "4 Vocal 4-4",
    src: "/audio/pro/enno-chunho/4 Vocal 4-4.mp3",
  },
  {
    id: 'enno-chunho-29',
    artist: 'enno-chunho',
    name: "5 Vocal 4-5",
    src: "/audio/pro/enno-chunho/5 Vocal 4-5.mp3",
  },
  {
    id: 'enno-chunho-30',
    artist: 'enno-chunho',
    name: "6 Vocal 4-6",
    src: "/audio/pro/enno-chunho/6 Vocal 4-6.mp3",
  },
  {
    id: 'enno-chunho-31',
    artist: 'enno-chunho',
    name: "7 Vocal 4-7",
    src: "/audio/pro/enno-chunho/7 Vocal 4-7.mp3",
  },
  {
    id: 'enno-chunho-32',
    artist: 'enno-chunho',
    name: "8 Vocal 4-8",
    src: "/audio/pro/enno-chunho/8 Vocal 4-8.mp3",
  },
  {
    id: 'enno-chunho-33',
    artist: 'enno-chunho',
    name: "AG Eb 1-1",
    src: "/audio/pro/enno-chunho/AG Eb 1-1.mp3",
  },
  {
    id: 'enno-chunho-34',
    artist: 'enno-chunho',
    name: "AG F 1-1",
    src: "/audio/pro/enno-chunho/AG F 1-1.mp3",
  },
  {
    id: 'enno-chunho-35',
    artist: 'enno-chunho',
    name: "AG G 1-1",
    src: "/audio/pro/enno-chunho/AG G 1-1.mp3",
  },
  {
    id: 'enno-chunho-36',
    artist: 'enno-chunho',
    name: "Bass C 1-1",
    src: "/audio/pro/enno-chunho/Bass C 1-1.mp3",
  },
  {
    id: 'enno-chunho-37',
    artist: 'enno-chunho',
    name: "Bass E 1-1",
    src: "/audio/pro/enno-chunho/Bass E 1-1.mp3",
  },
  {
    id: 'enno-chunho-38',
    artist: 'enno-chunho',
    name: "Bass Eb 1-1",
    src: "/audio/pro/enno-chunho/Bass Eb 1-1.mp3",
  },
  {
    id: 'enno-chunho-39',
    artist: 'enno-chunho',
    name: "Bass F 1-1",
    src: "/audio/pro/enno-chunho/Bass F 1-1.mp3",
  },
  {
    id: 'enno-chunho-40',
    artist: 'enno-chunho',
    name: "Bass G 1-1",
    src: "/audio/pro/enno-chunho/Bass G 1-1.mp3",
  },
  {
    id: 'enno-chunho-41',
    artist: 'enno-chunho',
    name: "Fx 1-1",
    src: "/audio/pro/enno-chunho/Fx 1-1.mp3",
  },
  {
    id: 'enno-chunho-42',
    artist: 'enno-chunho',
    name: "Fx 1-2",
    src: "/audio/pro/enno-chunho/Fx 1-2.mp3",
  },
  {
    id: 'enno-chunho-43',
    artist: 'enno-chunho',
    name: "Fx 1-3",
    src: "/audio/pro/enno-chunho/Fx 1-3.mp3",
  },
  {
    id: 'enno-chunho-44',
    artist: 'enno-chunho',
    name: "Fx 1-4",
    src: "/audio/pro/enno-chunho/Fx 1-4.mp3",
  },
  {
    id: 'enno-chunho-45',
    artist: 'enno-chunho',
    name: "HH 1-1",
    src: "/audio/pro/enno-chunho/HH 1-1.mp3",
  },
  {
    id: 'enno-chunho-46',
    artist: 'enno-chunho',
    name: "HH 1-2",
    src: "/audio/pro/enno-chunho/HH 1-2.mp3",
  },
  {
    id: 'enno-chunho-47',
    artist: 'enno-chunho',
    name: "Key 1-1",
    src: "/audio/pro/enno-chunho/Key 1-1.mp3",
  },
  {
    id: 'enno-chunho-48',
    artist: 'enno-chunho',
    name: "Key 1-2",
    src: "/audio/pro/enno-chunho/Key 1-2.mp3",
  },
  {
    id: 'enno-chunho-49',
    artist: 'enno-chunho',
    name: "Key 1-3",
    src: "/audio/pro/enno-chunho/Key 1-3.mp3",
  },
  {
    id: 'enno-chunho-50',
    artist: 'enno-chunho',
    name: "Key 1-4",
    src: "/audio/pro/enno-chunho/Key 1-4.mp3",
  },
  {
    id: 'enno-chunho-51',
    artist: 'enno-chunho',
    name: "Key 1-5",
    src: "/audio/pro/enno-chunho/Key 1-5.mp3",
  },
  {
    id: 'enno-chunho-52',
    artist: 'enno-chunho',
    name: "Kick 1-1",
    src: "/audio/pro/enno-chunho/Kick 1-1.mp3",
  },
  {
    id: 'enno-chunho-53',
    artist: 'enno-chunho',
    name: "Kick 1-2",
    src: "/audio/pro/enno-chunho/Kick 1-2.mp3",
  },
  {
    id: 'enno-chunho-54',
    artist: 'enno-chunho',
    name: "Pad 1-1",
    src: "/audio/pro/enno-chunho/Pad 1-1.mp3",
  },
  {
    id: 'enno-chunho-55',
    artist: 'enno-chunho',
    name: "Perc 1-1",
    src: "/audio/pro/enno-chunho/Perc 1-1.mp3",
  },
  {
    id: 'enno-chunho-56',
    artist: 'enno-chunho',
    name: "Perc 1-2",
    src: "/audio/pro/enno-chunho/Perc 1-2.mp3",
  },
  {
    id: 'l8ching-1',
    artist: 'l8ching',
    name: "1 Kick 1-1",
    src: "/audio/pro/l8ching/1 Kick 1-1.mp3",
  },
  {
    id: 'l8ching-2',
    artist: 'l8ching',
    name: "2 Clap 1-1",
    src: "/audio/pro/l8ching/2 Clap 1-1.mp3",
  },
  {
    id: 'l8ching-3',
    artist: 'l8ching',
    name: "3 Sd 1-1",
    src: "/audio/pro/l8ching/3 Sd 1-1.mp3",
  },
  {
    id: 'l8ching-4',
    artist: 'l8ching',
    name: "4 Bongo 1-1",
    src: "/audio/pro/l8ching/4 Bongo 1-1.mp3",
  },
  {
    id: 'l8ching-5',
    artist: 'l8ching',
    name: "5 Bongo 1-2",
    src: "/audio/pro/l8ching/5 Bongo 1-2.mp3",
  },
  {
    id: 'l8ching-6',
    artist: 'l8ching',
    name: "6 Anima 1-1",
    src: "/audio/pro/l8ching/6 Anima 1-1.mp3",
  },
  {
    id: 'l8ching-7',
    artist: 'l8ching',
    name: "7 Choir 1-1",
    src: "/audio/pro/l8ching/7 Choir 1-1.mp3",
  },
  {
    id: 'l8ching-8',
    artist: 'l8ching',
    name: "8 Choir 1-2",
    src: "/audio/pro/l8ching/8 Choir 1-2.mp3",
  },
  {
    id: 'l8ching-9',
    artist: 'l8ching',
    name: "1 Chime 2-1",
    src: "/audio/pro/l8ching/1 Chime 2-1.mp3",
  },
  {
    id: 'l8ching-10',
    artist: 'l8ching',
    name: "2 FT 2-1",
    src: "/audio/pro/l8ching/2 FT 2-1.mp3",
  },
  {
    id: 'l8ching-11',
    artist: 'l8ching',
    name: "3 Perc 2-1",
    src: "/audio/pro/l8ching/3 Perc 2-1.mp3",
  },
  {
    id: 'l8ching-12',
    artist: 'l8ching',
    name: "4 Perc 2-2",
    src: "/audio/pro/l8ching/4 Perc 2-2.mp3",
  },
  {
    id: 'l8ching-13',
    artist: 'l8ching',
    name: "5 Perc 2-3",
    src: "/audio/pro/l8ching/5 Perc 2-3.mp3",
  },
  {
    id: 'l8ching-14',
    artist: 'l8ching',
    name: "6 Rs 2-1",
    src: "/audio/pro/l8ching/6 Rs 2-1.mp3",
  },
  {
    id: 'l8ching-15',
    artist: 'l8ching',
    name: "7 Shell 2-1",
    src: "/audio/pro/l8ching/7 Shell 2-1.mp3",
  },
  {
    id: 'l8ching-16',
    artist: 'l8ching',
    name: "8 Water 2-1",
    src: "/audio/pro/l8ching/8 Water 2-1.mp3",
  },
  {
    id: 'l8ching-17',
    artist: 'l8ching',
    name: "1 Kick 3-1",
    src: "/audio/pro/l8ching/1 Kick 3-1.mp3",
  },
  {
    id: 'l8ching-18',
    artist: 'l8ching',
    name: "2 Rim 3-1",
    src: "/audio/pro/l8ching/2 Rim 3-1.mp3",
  },
  {
    id: 'l8ching-19',
    artist: 'l8ching',
    name: "3 Sd 3-1",
    src: "/audio/pro/l8ching/3 Sd 3-1.mp3",
  },
  {
    id: 'l8ching-20',
    artist: 'l8ching',
    name: "4 Conga 3-1",
    src: "/audio/pro/l8ching/4 Conga 3-1.mp3",
  },
  {
    id: 'l8ching-21',
    artist: 'l8ching',
    name: "5 Conga 3-2",
    src: "/audio/pro/l8ching/5 Conga 3-2.mp3",
  },
  {
    id: 'l8ching-22',
    artist: 'l8ching',
    name: "6 HH 3-1",
    src: "/audio/pro/l8ching/6 HH 3-1.mp3",
  },
  {
    id: 'l8ching-23',
    artist: 'l8ching',
    name: "7 Tic Tac 3-1",
    src: "/audio/pro/l8ching/7 Tic Tac 3-1.mp3",
  },
  {
    id: 'l8ching-24',
    artist: 'l8ching',
    name: "8 Tic Tac 3-2",
    src: "/audio/pro/l8ching/8 Tic Tac 3-2.mp3",
  },
  {
    id: 'l8ching-25',
    artist: 'l8ching',
    name: "1 Kick 4-1",
    src: "/audio/pro/l8ching/1 Kick 4-1.mp3",
  },
  {
    id: 'l8ching-26',
    artist: 'l8ching',
    name: "2 Rim 4-1",
    src: "/audio/pro/l8ching/2 Rim 4-1.mp3",
  },
  {
    id: 'l8ching-27',
    artist: 'l8ching',
    name: "3 EP 4-1",
    src: "/audio/pro/l8ching/3 EP 4-1.mp3",
  },
  {
    id: 'l8ching-28',
    artist: 'l8ching',
    name: "4 Leaf 4-1",
    src: "/audio/pro/l8ching/4 Leaf 4-1.mp3",
  },
  {
    id: 'l8ching-29',
    artist: 'l8ching',
    name: "5 Leaf 4-2",
    src: "/audio/pro/l8ching/5 Leaf 4-2.mp3",
  },
  {
    id: 'l8ching-30',
    artist: 'l8ching',
    name: "6 Shaker 4-1",
    src: "/audio/pro/l8ching/6 Shaker 4-1.mp3",
  },
  {
    id: 'l8ching-31',
    artist: 'l8ching',
    name: "7 Wood 4-1",
    src: "/audio/pro/l8ching/7 Wood 4-1.mp3",
  },
  {
    id: 'l8ching-32',
    artist: 'l8ching',
    name: "8 Wood 4-2",
    src: "/audio/pro/l8ching/8 Wood 4-2.mp3",
  },
  {
    id: 'l8ching-33',
    artist: 'l8ching',
    name: "AG 4-1",
    src: "/audio/pro/l8ching/AG 4-1.mp3",
  },
  {
    id: 'l8ching-34',
    artist: 'l8ching',
    name: "AG 4-2",
    src: "/audio/pro/l8ching/AG 4-2.mp3",
  },
  {
    id: 'l8ching-35',
    artist: 'l8ching',
    name: "AG 4-4",
    src: "/audio/pro/l8ching/AG 4-4.mp3",
  },
  {
    id: 'l8ching-36',
    artist: 'l8ching',
    name: "Bass Ab 3-1",
    src: "/audio/pro/l8ching/Bass Ab 3-1.mp3",
  },
  {
    id: 'l8ching-37',
    artist: 'l8ching',
    name: "Bass B 1-1",
    src: "/audio/pro/l8ching/Bass B 1-1.mp3",
  },
  {
    id: 'l8ching-38',
    artist: 'l8ching',
    name: "Bass B 1-2",
    src: "/audio/pro/l8ching/Bass B 1-2.mp3",
  },
  {
    id: 'l8ching-39',
    artist: 'l8ching',
    name: "Bass Bb 3-1",
    src: "/audio/pro/l8ching/Bass Bb 3-1.mp3",
  },
  {
    id: 'l8ching-40',
    artist: 'l8ching',
    name: "Bass C 3-1",
    src: "/audio/pro/l8ching/Bass C 3-1.mp3",
  },
  {
    id: 'l8ching-41',
    artist: 'l8ching',
    name: "Bass C# 1-1",
    src: "/audio/pro/l8ching/Bass C^ 1-1.mp3",
  },
  {
    id: 'l8ching-42',
    artist: 'l8ching',
    name: "Bass C# 3-1",
    src: "/audio/pro/l8ching/Bass C^ 3-1.mp3",
  },
  {
    id: 'l8ching-43',
    artist: 'l8ching',
    name: "Bass D 3-1",
    src: "/audio/pro/l8ching/Bass D 3-1.mp3",
  },
  {
    id: 'l8ching-44',
    artist: 'l8ching',
    name: "Bass E 1-1",
    src: "/audio/pro/l8ching/Bass E 1-1.mp3",
  },
  {
    id: 'l8ching-45',
    artist: 'l8ching',
    name: "Bass E 1-2",
    src: "/audio/pro/l8ching/Bass E 1-2.mp3",
  },
  {
    id: 'l8ching-46',
    artist: 'l8ching',
    name: "Bass Eb 3-1",
    src: "/audio/pro/l8ching/Bass Eb 3-1.mp3",
  },
  {
    id: 'l8ching-47',
    artist: 'l8ching',
    name: "Bass F 3-1",
    src: "/audio/pro/l8ching/Bass F 3-1.mp3",
  },
  {
    id: 'l8ching-48',
    artist: 'l8ching',
    name: "Bass F# 1-1",
    src: "/audio/pro/l8ching/Bass F^ 1-1.mp3",
  },
  {
    id: 'l8ching-49',
    artist: 'l8ching',
    name: "Bass F# 1-2",
    src: "/audio/pro/l8ching/Bass F^ 1-2.mp3",
  },
  {
    id: 'l8ching-50',
    artist: 'l8ching',
    name: "Bass G 3-1",
    src: "/audio/pro/l8ching/Bass G 3-1.mp3",
  },
  {
    id: 'l8ching-51',
    artist: 'l8ching',
    name: "Choir 1-2",
    src: "/audio/pro/l8ching/Choir 1-2.mp3",
  },
  {
    id: 'l8ching-52',
    artist: 'l8ching',
    name: "Chord 1-1",
    src: "/audio/pro/l8ching/Chord 1-1.mp3",
  },
  {
    id: 'l8ching-53',
    artist: 'l8ching',
    name: "Chord 1-2",
    src: "/audio/pro/l8ching/Chord 1-2.mp3",
  },
  {
    id: 'l8ching-54',
    artist: 'l8ching',
    name: "Chord 1-3",
    src: "/audio/pro/l8ching/Chord 1-3.mp3",
  },
  {
    id: 'l8ching-55',
    artist: 'l8ching',
    name: "Chord 1-4",
    src: "/audio/pro/l8ching/Chord 1-4.mp3",
  },
  {
    id: 'l8ching-56',
    artist: 'l8ching',
    name: "Chord 1-5",
    src: "/audio/pro/l8ching/Chord 1-5.mp3",
  },
  {
    id: 'l8ching-57',
    artist: 'l8ching',
    name: "Crash 4-1",
    src: "/audio/pro/l8ching/Crash 4-1.mp3",
  },
  {
    id: 'l8ching-58',
    artist: 'l8ching',
    name: "Crash 4-2",
    src: "/audio/pro/l8ching/Crash 4-2.mp3",
  },
  {
    id: 'l8ching-59',
    artist: 'l8ching',
    name: "EG 4-1",
    src: "/audio/pro/l8ching/EG 4-1.mp3",
  },
  {
    id: 'l8ching-60',
    artist: 'l8ching',
    name: "EG 4-2",
    src: "/audio/pro/l8ching/EG 4-2.mp3",
  },
  {
    id: 'l8ching-61',
    artist: 'l8ching',
    name: "EG 4-3",
    src: "/audio/pro/l8ching/EG 4-3.mp3",
  },
  {
    id: 'l8ching-62',
    artist: 'l8ching',
    name: "EG 4-5",
    src: "/audio/pro/l8ching/EG 4-5.mp3",
  },
  {
    id: 'l8ching-63',
    artist: 'l8ching',
    name: "EG Bb 3-1",
    src: "/audio/pro/l8ching/EG Bb 3-1.mp3",
  },
  {
    id: 'l8ching-64',
    artist: 'l8ching',
    name: "EG C# 3-1",
    src: "/audio/pro/l8ching/EG C^ 3-1.mp3",
  },
  {
    id: 'l8ching-65',
    artist: 'l8ching',
    name: "EG F 3-1",
    src: "/audio/pro/l8ching/EG F 3-1.mp3",
  },
  {
    id: 'l8ching-66',
    artist: 'l8ching',
    name: "EP 4-1",
    src: "/audio/pro/l8ching/EP 4-1.mp3",
  },
  {
    id: 'l8ching-67',
    artist: 'l8ching',
    name: "EP 4-2",
    src: "/audio/pro/l8ching/EP 4-2.mp3",
  },
  {
    id: 'l8ching-68',
    artist: 'l8ching',
    name: "EP 4-3",
    src: "/audio/pro/l8ching/EP 4-3.mp3",
  },
  {
    id: 'l8ching-69',
    artist: 'l8ching',
    name: "EP 4-4",
    src: "/audio/pro/l8ching/EP 4-4.mp3",
  },
  {
    id: 'l8ching-70',
    artist: 'l8ching',
    name: "EP 4-5",
    src: "/audio/pro/l8ching/EP 4-5.mp3",
  },
  {
    id: 'l8ching-71',
    artist: 'l8ching',
    name: "Hihat 1-1",
    src: "/audio/pro/l8ching/Hihat 1-1.mp3",
  },
  {
    id: 'l8ching-72',
    artist: 'l8ching',
    name: "Perc 2-1",
    src: "/audio/pro/l8ching/Perc 2-1.mp3",
  },
  {
    id: 'l8ching-73',
    artist: 'l8ching',
    name: "Piano 3-1",
    src: "/audio/pro/l8ching/Piano 3-1.mp3",
  },
  {
    id: 'l8ching-74',
    artist: 'l8ching',
    name: "SK 3-1",
    src: "/audio/pro/l8ching/SK 3-1.mp3",
  },
  {
    id: 'l8ching-75',
    artist: 'l8ching',
    name: "Wood 3-1",
    src: "/audio/pro/l8ching/Wood 3-1.mp3",
  },
  {
    id: 'l8ching-76',
    artist: 'l8ching',
    name: "Wood 3-2",
    src: "/audio/pro/l8ching/Wood 3-2.mp3",
  },
  {
    id: 'l8ching-77',
    artist: 'l8ching',
    name: "Wood 3-3",
    src: "/audio/pro/l8ching/Wood 3-3.mp3",
  },
  {
    id: 'sonia-1',
    artist: 'sonia',
    name: "1 Kick 1-1",
    src: "/audio/pro/sonia/1 Kick 1-1.mp3",
  },
  {
    id: 'sonia-2',
    artist: 'sonia',
    name: "2 Tom 1-1",
    src: "/audio/pro/sonia/2 Tom 1-1.mp3",
  },
  {
    id: 'sonia-3',
    artist: 'sonia',
    name: "3 Snare 1-1",
    src: "/audio/pro/sonia/3 Snare 1-1.mp3",
  },
  {
    id: 'sonia-4',
    artist: 'sonia',
    name: "4 FX 1-1",
    src: "/audio/pro/sonia/4 FX 1-1.mp3",
  },
  {
    id: 'sonia-5',
    artist: 'sonia',
    name: "5 TH 1-1",
    src: "/audio/pro/sonia/5 TH 1-1.mp3",
  },
  {
    id: 'sonia-6',
    artist: 'sonia',
    name: "6 WHAT 1-1",
    src: "/audio/pro/sonia/6 WHAT 1-1.mp3",
  },
  {
    id: 'sonia-7',
    artist: 'sonia',
    name: "7 WN 1-1",
    src: "/audio/pro/sonia/7 WN 1-1.mp3",
  },
  {
    id: 'sonia-8',
    artist: 'sonia',
    name: "8 TH 1-2",
    src: "/audio/pro/sonia/8 TH 1-2.mp3",
  },
  {
    id: 'sonia-9',
    artist: 'sonia',
    name: "1 Laser 2-1",
    src: "/audio/pro/sonia/1 Laser 2-1.mp3",
  },
  {
    id: 'sonia-10',
    artist: 'sonia',
    name: "2 Pluck 2-1",
    src: "/audio/pro/sonia/2 Pluck 2-1.mp3",
  },
  {
    id: 'sonia-11',
    artist: 'sonia',
    name: "3 Pluck 2-2",
    src: "/audio/pro/sonia/3 Pluck 2-2.mp3",
  },
  {
    id: 'sonia-12',
    artist: 'sonia',
    name: "4 Pluck 2-3",
    src: "/audio/pro/sonia/4 Pluck 2-3.mp3",
  },
  {
    id: 'sonia-13',
    artist: 'sonia',
    name: "5 CowBell 2-1",
    src: "/audio/pro/sonia/5 CowBell 2-1.mp3",
  },
  {
    id: 'sonia-14',
    artist: 'sonia',
    name: "6 Pluck 2-4",
    src: "/audio/pro/sonia/6 Pluck 2-4.mp3",
  },
  {
    id: 'sonia-15',
    artist: 'sonia',
    name: "7 Pluck 2-5",
    src: "/audio/pro/sonia/7 Pluck 2-5.mp3",
  },
  {
    id: 'sonia-16',
    artist: 'sonia',
    name: "8 Pluck 2-6",
    src: "/audio/pro/sonia/8 Pluck 2-6.mp3",
  },
  {
    id: 'sonia-17',
    artist: 'sonia',
    name: "1 Key 3-1",
    src: "/audio/pro/sonia/1 Key 3-1.mp3",
  },
  {
    id: 'sonia-18',
    artist: 'sonia',
    name: "2 HB 1-1",
    src: "/audio/pro/sonia/2 HB 1-1.mp3",
  },
  {
    id: 'sonia-19',
    artist: 'sonia',
    name: "3 Metal 3-1",
    src: "/audio/pro/sonia/3 Metal 3-1.mp3",
  },
  {
    id: 'sonia-20',
    artist: 'sonia',
    name: "4 DS 3-1",
    src: "/audio/pro/sonia/4 DS 3-1.mp3",
  },
  {
    id: 'sonia-21',
    artist: 'sonia',
    name: "5 Key 3-2",
    src: "/audio/pro/sonia/5 Key 3-2.mp3",
  },
  {
    id: 'sonia-22',
    artist: 'sonia',
    name: "6 TH 3-1",
    src: "/audio/pro/sonia/6 TH 3-1.mp3",
  },
  {
    id: 'sonia-23',
    artist: 'sonia',
    name: "7 Dong 3-1",
    src: "/audio/pro/sonia/7 Dong 3-1.mp3",
  },
  {
    id: 'sonia-24',
    artist: 'sonia',
    name: "8 ST 3-2",
    src: "/audio/pro/sonia/8 ST 3-2.mp3",
  },
  {
    id: 'sonia-25',
    artist: 'sonia',
    name: "1 Crash 4-1",
    src: "/audio/pro/sonia/1 Crash 4-1.mp3",
  },
  {
    id: 'sonia-26',
    artist: 'sonia',
    name: "2 Pluck 4-1",
    src: "/audio/pro/sonia/2 Pluck 4-1.mp3",
  },
  {
    id: 'sonia-27',
    artist: 'sonia',
    name: "3 Pluck 4-2",
    src: "/audio/pro/sonia/3 Pluck 4-2.mp3",
  },
  {
    id: 'sonia-28',
    artist: 'sonia',
    name: "4 Pluck 4-3",
    src: "/audio/pro/sonia/4 Pluck 4-3.mp3",
  },
  {
    id: 'sonia-29',
    artist: 'sonia',
    name: "5 Impact 4-1",
    src: "/audio/pro/sonia/5 Impact 4-1.mp3",
  },
  {
    id: 'sonia-30',
    artist: 'sonia',
    name: "6 Pluck 4-4",
    src: "/audio/pro/sonia/6 Pluck 4-4.mp3",
  },
  {
    id: 'sonia-31',
    artist: 'sonia',
    name: "7 Pluck 4-5",
    src: "/audio/pro/sonia/7 Pluck 4-5.mp3",
  },
  {
    id: 'sonia-32',
    artist: 'sonia',
    name: "8 Pluck 4-6",
    src: "/audio/pro/sonia/8 Pluck 4-6.mp3",
  },
  {
    id: 'sonia-33',
    artist: 'sonia',
    name: "HH 1-1",
    src: "/audio/pro/sonia/HH 1-1.mp3",
  },
  {
    id: 'sonia-34',
    artist: 'sonia',
    name: "HH 1-2",
    src: "/audio/pro/sonia/HH 1-2.mp3",
  },
  {
    id: 'sonia-35',
    artist: 'sonia',
    name: "HH 1-3",
    src: "/audio/pro/sonia/HH 1-3.mp3",
  },
  {
    id: 'sonia-36',
    artist: 'sonia',
    name: "HH 1-4",
    src: "/audio/pro/sonia/HH 1-4.mp3",
  },
  {
    id: 'sonia-37',
    artist: 'sonia',
    name: "Kick 1-1",
    src: "/audio/pro/sonia/Kick 1-1.mp3",
  },
  {
    id: 'sonia-38',
    artist: 'sonia',
    name: "Kick 1-2",
    src: "/audio/pro/sonia/Kick 1-2.mp3",
  },
  {
    id: 'sonia-39',
    artist: 'sonia',
    name: "Kick 1-3",
    src: "/audio/pro/sonia/Kick 1-3.mp3",
  },
  {
    id: 'sonia-40',
    artist: 'sonia',
    name: "Snare 1-1",
    src: "/audio/pro/sonia/Snare 1-1.mp3",
  },
  {
    id: 'sonia-41',
    artist: 'sonia',
    name: "Snare 1-2",
    src: "/audio/pro/sonia/Snare 1-2.mp3",
  },
];

export default proSamples;
