const gifs: { [key: string]: any } = {
  puzzleman: {
    seq1: {
      "1": "/images/gif/puzzleman/puzzleman_seq1_sample01_Kick.webp",
      "2": "/images/gif/puzzleman/puzzleman_seq1_sample02_Snare.webp",
      "3": "/images/gif/puzzleman/puzzleman_seq1_sample03_Hihat.webp",
      "4": "/images/gif/puzzleman/puzzleman_seq1_sample04_Open hihat.webp",
      "5": "/images/gif/puzzleman/puzzleman_seq1_sample05_Cowbell.webp",
      "6": "/images/gif/puzzleman/puzzleman_seq1_sample06_Bongo.webp",
      "7": "/images/gif/puzzleman/puzzleman_seq1_sample07_Bongo2.webp",
      "8": "/images/gif/puzzleman/puzzleman_seq1_sample08_Trumpet.webp",
      wait: "/images/gif/puzzleman/puzzleman_seq1_waiting.webp",
    },
    seq2: {
      "1": "/images/gif/puzzleman/puzzleman_seq1_sample01_Kick.webp",
      "2": "/images/gif/puzzleman/puzzleman_seq1_sample02_Snare.webp",
      "3": "/images/gif/puzzleman/puzzleman_seq1_sample03_Hihat.webp",
      "4": "/images/gif/puzzleman/puzzleman_seq1_sample04_Open hihat.webp",
      "5": "/images/gif/puzzleman/puzzleman_seq1_sample05_Cowbell.webp",
      "6": "/images/gif/puzzleman/puzzleman_seq1_sample06_Bongo.webp",
      "7": "/images/gif/puzzleman/puzzleman_seq1_sample07_Bongo2.webp",
      "8": "/images/gif/puzzleman/puzzleman_seq1_sample08_Trumpet.webp",
      wait: "/images/gif/puzzleman/puzzleman_seq1_waiting.webp",
    },
    seq3: {
      "1": "/images/gif/puzzleman/puzzleman_seq1_sample01_Kick.webp",
      "2": "/images/gif/puzzleman/puzzleman_seq1_sample02_Snare.webp",
      "3": "/images/gif/puzzleman/puzzleman_seq1_sample03_Hihat.webp",
      "4": "/images/gif/puzzleman/puzzleman_seq1_sample04_Open hihat.webp",
      "5": "/images/gif/puzzleman/puzzleman_seq1_sample05_Cowbell.webp",
      "6": "/images/gif/puzzleman/puzzleman_seq1_sample06_Bongo.webp",
      "7": "/images/gif/puzzleman/puzzleman_seq1_sample07_Bongo2.webp",
      "8": "/images/gif/puzzleman/puzzleman_seq1_sample08_Trumpet.webp",
      wait: "/images/gif/puzzleman/puzzleman_seq1_waiting.webp",
    },
    seq4: {
      "1": "/images/gif/puzzleman/puzzleman_seq1_sample01_Kick.webp",
      "2": "/images/gif/puzzleman/puzzleman_seq1_sample02_Snare.webp",
      "3": "/images/gif/puzzleman/puzzleman_seq1_sample03_Hihat.webp",
      "4": "/images/gif/puzzleman/puzzleman_seq1_sample04_Open hihat.webp",
      "5": "/images/gif/puzzleman/puzzleman_seq1_sample05_Cowbell.webp",
      "6": "/images/gif/puzzleman/puzzleman_seq1_sample06_Bongo.webp",
      "7": "/images/gif/puzzleman/puzzleman_seq1_sample07_Bongo2.webp",
      "8": "/images/gif/puzzleman/puzzleman_seq1_sample08_Trumpet.webp",
      wait: "/images/gif/puzzleman/puzzleman_seq1_waiting.webp",
    },
  },
  "sunset-rollercoaster": {
    seq1: {
      "1": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample01.webp",
      "2": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample02.webp",
      "3": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample03.webp",
      "4": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample04.webp",
      "5": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample05.webp",
      "6": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample06.webp",
      "7": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample07.webp",
      "8": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample08.webp",
      wait: "/images/gif/sunset-rollercoaster/sunset-rollercoasterjam.webp",
    },
    seq2: {
      "1": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample01.webp",
      "2": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample02.webp",
      "3": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample03.webp",
      "4": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample04.webp",
      "5": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample05.webp",
      "6": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample06.webp",
      "7": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample07.webp",
      "8": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample08.webp",
      wait: "/images/gif/sunset-rollercoaster/sunset-rollercoasterjam.webp",
    },
    seq3: {
      "1": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample01.webp",
      "2": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample02.webp",
      "3": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample03.webp",
      "4": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample04.webp",
      "5": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample05.webp",
      "6": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample06.webp",
      "7": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample07.webp",
      "8": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample08.webp",
      wait: "/images/gif/sunset-rollercoaster/sunset-rollercoasterjam.webp",
    },
    seq4: {
      "1": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample01.webp",
      "2": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample02.webp",
      "3": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample03.webp",
      "4": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample04.webp",
      "5": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample05.webp",
      "6": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample06.webp",
      "7": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample07.webp",
      "8": "/images/gif/sunset-rollercoaster/sunset-rollercoaster_seq1_sample08.webp",
      wait: "/images/gif/sunset-rollercoaster/sunset-rollercoasterjam.webp",
    },
  },
  "enno-chunho": {
    seq1: {
      "1": "/images/gif/enno-chunho/enno_seq1_sample01_Fly_1(暫留在畫面).webp",
      "2": "/images/gif/enno-chunho/enno_seq1_sample02_Fly_2(暫留在畫面).webp",
      "3": "/images/gif/enno-chunho/enno_seq1_sample03_Fly_3.webp",
      "4": "/images/gif/enno-chunho/enno_seq1_sample04_Fly_4.webp",
      "5": "/images/gif/enno-chunho/enno_seq1_sample05_darling(暫留在畫面).webp",
      "6": "/images/gif/enno-chunho/enno_seq1_sample06_愛(透明度65).webp",
      "7": "/images/gif/enno-chunho/enno_seq1_sample07_新世界(暫留在畫面).webp",
      "8": "/images/gif/enno-chunho/enno_seq1_sample08_Fx(覆蓋之前全部圖).webp",
      wait: "/images/gif/enno-chunho/enno_seq1_BG.webp",
      spark: "/images/gif/enno-chunho/enno_seq1_spark.webp",
    },
    seq2: {
      "1": "/images/gif/enno-chunho/enno_seq2_sample01_(透明度65).webp",
      "2": "/images/gif/enno-chunho/enno_seq2_sample02_月娘(暫留在畫面).webp",
      "3": "/images/gif/enno-chunho/enno_seq2_sample03_一世人(暫留在畫面).webp",
      "4": "/images/gif/enno-chunho/enno_seq2_sample04_咱的路(暫留在畫面).webp",
      "5": "/images/gif/enno-chunho/enno_seq2_sample05_Umm_1.webp",
      "6": "/images/gif/enno-chunho/enno_seq2_sample06_Umm_2.webp",
      "7": "/images/gif/enno-chunho/enno_seq2_sample07_(覆蓋之前全部圖).webp",
      "8": "/images/gif/enno-chunho/enno_seq2_sample08_Fx(暫留在畫面).webp",
      wait: "/images/gif/enno-chunho/enno_seq2_BG1.webp",
      spark: "/images/gif/enno-chunho/enno_seq2_spark.webp",
    },
    seq3: {
      "1": "/images/gif/enno-chunho/enno_seq3_sample01_就算我.(暫留在畫面).webp",
      "2": "/images/gif/enno-chunho/enno_seq3_sample02_請你別(暫留在畫面).webp",
      "3": "/images/gif/enno-chunho/enno_seq3_sample03_就算我_2(暫留在畫面).webp",
      "4": "/images/gif/enno-chunho/enno_seq3_sample04_請你別_2(暫留在畫面).webp",
      "5": "/images/gif/enno-chunho/enno_seq3_sample05_Umm_1(暫留在畫面).webp",
      "6": "/images/gif/enno-chunho/enno_seq3_sample06_Umm_2.webp",
      "7": "/images/gif/enno-chunho/enno_seq3_sample07_Umm_3.webp",
      "8": "/images/gif/enno-chunho/enno_seq3_sample08_Umm_4.webp",
      wait: "/images/gif/enno-chunho/enno_seq3_BG.webp",
    },
    seq4: {
      "1": "/images/gif/enno-chunho/enno_seq4_sample01_我會聽(暫留在畫面).webp",
      "2": "/images/gif/enno-chunho/enno_seq4_sample02_在夜晚(暫留在畫面).webp",
      "3": "/images/gif/enno-chunho/enno_seq4_sample03_的盡頭(暫留在畫面).webp",
      "4": "/images/gif/enno-chunho/enno_seq4_sample04_我(暫留在畫面).webp",
      "5": "/images/gif/enno-chunho/enno_seq4_sample05_會(暫留在畫面).webp",
      "6": "/images/gif/enno-chunho/enno_seq4_sample06_聽(暫留在畫面).webp",
      "7": "/images/gif/enno-chunho/enno_seq4_sample07_你(暫留在畫面).webp",
      "8": "/images/gif/enno-chunho/enno_seq4_sample08_說(暫留在畫面).webp",
      wait: "/images/gif/enno-chunho/enno_seq4_White BG.webp",
      dust: "/images/gif/enno-chunho/enno_seq4_dust(最前面).webp",
    },

  },
  l8ching: {
    seq1: {
      "1": "/images/gif/l8ching/l8ching_seq1_sample01_kick.webp",
      "2": "/images/gif/l8ching/l8ching_seq1_sample02_clap1.webp",
      "3": "/images/gif/l8ching/l8ching_seq1_sample03_snare.webp",
      "4": "/images/gif/l8ching/l8ching_seq1_sample04_bongo.webp",
      "5": "/images/gif/l8ching/l8ching_seq1_sample05_conga1.webp",
      "6": "/images/gif/l8ching/l8ching_seq1_sample06_animal.webp",
      "7": "/images/gif/l8ching/l8ching_seq1_sample07_choir_1.webp",
      "8": "/images/gif/l8ching/l8ching_seq1_sample08_choir_2.webp",
      wait: "/images/gif/l8ching/l8ching_waiting.webp",
    },
    seq2: {
      "1": "/images/gif/l8ching/l8ching_seq1_sample01_kick.webp",
      "2": "/images/gif/l8ching/l8ching_seq1_sample02_clap1.webp",
      "3": "/images/gif/l8ching/l8ching_seq1_sample03_snare.webp",
      "4": "/images/gif/l8ching/l8ching_seq1_sample04_bongo.webp",
      "5": "/images/gif/l8ching/l8ching_seq1_sample05_conga1.webp",
      "6": "/images/gif/l8ching/l8ching_seq1_sample06_animal.webp",
      "7": "/images/gif/l8ching/l8ching_seq1_sample07_choir_1.webp",
      "8": "/images/gif/l8ching/l8ching_seq1_sample08_choir_2.webp",
      wait: "/images/gif/l8ching/l8ching_waiting.webp",
    },
    seq3: {
      "1": "/images/gif/l8ching/l8ching_seq1_sample01_kick.webp",
      "2": "/images/gif/l8ching/l8ching_seq1_sample02_clap1.webp",
      "3": "/images/gif/l8ching/l8ching_seq1_sample03_snare.webp",
      "4": "/images/gif/l8ching/l8ching_seq1_sample04_bongo.webp",
      "5": "/images/gif/l8ching/l8ching_seq1_sample05_conga1.webp",
      "6": "/images/gif/l8ching/l8ching_seq1_sample06_animal.webp",
      "7": "/images/gif/l8ching/l8ching_seq1_sample07_choir_1.webp",
      "8": "/images/gif/l8ching/l8ching_seq1_sample08_choir_2.webp",
      wait: "/images/gif/l8ching/l8ching_waiting.webp",
    },
    seq4: {
      "1": "/images/gif/l8ching/l8ching_seq1_sample01_kick.webp",
      "2": "/images/gif/l8ching/l8ching_seq1_sample02_clap1.webp",
      "3": "/images/gif/l8ching/l8ching_seq1_sample03_snare.webp",
      "4": "/images/gif/l8ching/l8ching_seq1_sample04_bongo.webp",
      "5": "/images/gif/l8ching/l8ching_seq1_sample05_conga1.webp",
      "6": "/images/gif/l8ching/l8ching_seq1_sample06_animal.webp",
      "7": "/images/gif/l8ching/l8ching_seq1_sample07_choir_1.webp",
      "8": "/images/gif/l8ching/l8ching_seq1_sample08_choir_2.webp",
      wait: "/images/gif/l8ching/l8ching_waiting.webp",
    },

  },
  sonia: {
    seq1: {
      "1": "/images/gif/sonia/sonia_seq1_sample01_clap.webp",
      "2": "/images/gif/sonia/sonia_seq1_sample02_horn-bass_1.webp",
      "3": "/images/gif/sonia/sonia_seq1_sample03_horn-bass_2.webp",
      "4": "/images/gif/sonia/sonia_seq1_sample04_horn-bass_3.webp",
      "5": "/images/gif/sonia/sonia_seq1_sample05_bass-drop.webp",
      "6": "/images/gif/sonia/sonia_seq1_sample06_the-ha.webp",
      "7": "/images/gif/sonia/sonia_seq1_sample07_what.webp",
      "8": "/images/gif/sonia/sonia_seq1_sample08_white-noise.webp",
      wait: "/images/gif/sonia/sonia-bg-fast-dark.webp",
      walk: "/images/gif/sonia/sonia-walk-2-fast-bright.webp",
      dark: "/images/gif/sonia/sonia calico-more dark.webp",
    },
    seq2: {
      "1": "/images/gif/sonia/sonia_seq1_sample01_clap.webp",
      "2": "/images/gif/sonia/sonia_seq1_sample02_horn-bass_1.webp",
      "3": "/images/gif/sonia/sonia_seq1_sample03_horn-bass_2.webp",
      "4": "/images/gif/sonia/sonia_seq1_sample04_horn-bass_3.webp",
      "5": "/images/gif/sonia/sonia_seq1_sample05_bass-drop.webp",
      "6": "/images/gif/sonia/sonia_seq1_sample06_the-ha.webp",
      "7": "/images/gif/sonia/sonia_seq1_sample07_what.webp",
      "8": "/images/gif/sonia/sonia_seq1_sample08_white-noise.webp",
      wait: "/images/gif/sonia/sonia-bg-fast-dark.webp",
      walk: "/images/gif/sonia/sonia-walk-2-fast-bright.webp",
      dark: "/images/gif/sonia/sonia calico-more dark.webp",
    },
    seq3: {
      "1": "/images/gif/sonia/sonia_seq1_sample01_clap.webp",
      "2": "/images/gif/sonia/sonia_seq1_sample02_horn-bass_1.webp",
      "3": "/images/gif/sonia/sonia_seq1_sample03_horn-bass_2.webp",
      "4": "/images/gif/sonia/sonia_seq1_sample04_horn-bass_3.webp",
      "5": "/images/gif/sonia/sonia_seq1_sample05_bass-drop.webp",
      "6": "/images/gif/sonia/sonia_seq1_sample06_the-ha.webp",
      "7": "/images/gif/sonia/sonia_seq1_sample07_what.webp",
      "8": "/images/gif/sonia/sonia_seq1_sample08_white-noise.webp",
      wait: "/images/gif/sonia/sonia-bg-fast-dark.webp",
      walk: "/images/gif/sonia/sonia-walk-2-fast-bright.webp",
      dark: "/images/gif/sonia/sonia calico-more dark.webp",
    },
    seq4: {
      "1": "/images/gif/sonia/sonia_seq1_sample01_clap.webp",
      "2": "/images/gif/sonia/sonia_seq1_sample02_horn-bass_1.webp",
      "3": "/images/gif/sonia/sonia_seq1_sample03_horn-bass_2.webp",
      "4": "/images/gif/sonia/sonia_seq1_sample04_horn-bass_3.webp",
      "5": "/images/gif/sonia/sonia_seq1_sample05_bass-drop.webp",
      "6": "/images/gif/sonia/sonia_seq1_sample06_the-ha.webp",
      "7": "/images/gif/sonia/sonia_seq1_sample07_what.webp",
      "8": "/images/gif/sonia/sonia_seq1_sample08_white-noise.webp",
      wait: "/images/gif/sonia/sonia-bg-fast-dark.webp",
      walk: "/images/gif/sonia/sonia-walk-2-fast-bright.webp",
      dark: "/images/gif/sonia/sonia calico-more dark.webp",
    },
  },
};

export default gifs;
